import { env } from "cloudflare:workers";import { NextResponse } from "next/server";import { isAdmin } from "@/lib/admin-auth";import { syncProviderCatalog } from "@/lib/provider-catalog";import { providerConfigured } from "@/lib/provider";
type Input={id?:number;platform?:string;category?:string;name?:string;providerServiceId?:string;minOrder?:number;maxOrder?:number;costPrice?:number;salePrice?:number;priceUnit?:string;description?:string;active?:boolean};const cents=(v:unknown)=>Math.max(0,Math.round(Number(v||0)*100));
export async function GET(){
 const base="SELECT id,platform,category,name,provider_service_id providerServiceId,min_order minOrder,max_order maxOrder,cost_price costPrice,sale_price salePrice,price_unit priceUnit,provider_features providerFeatures,provider_fields providerFields,average_time_seconds averageTimeSeconds,description,active,created_at createdAt FROM services ORDER BY id DESC";
 const read=async()=>{try{return await env.DB.prepare(base.replace(" FROM services"," ,(SELECT COUNT(*) FROM orders o WHERE o.service_id=services.id) orderCount FROM services")).all()}catch{const fallback:any=await env.DB.prepare(base).all();fallback.results=(fallback.results as any[]).map(x=>({...x,orderCount:0}));return fallback}};
 let q:any=await read(),syncError="",newServicesSince=Math.floor(Date.now()/1000);try{const baseline:any=await env.DB.prepare("SELECT value FROM site_settings WHERE key='provider_catalog_new_services_since'").first();newServicesSince=Number(baseline?.value||0);if(!newServicesSince){newServicesSince=Math.floor(Date.now()/1000);await env.DB.prepare("INSERT INTO site_settings(key,value,updated_at) VALUES('provider_catalog_new_services_since',?,?) ON CONFLICT(key) DO NOTHING").bind(String(newServicesSince),newServicesSince).run()}}catch{}
 if(providerConfigured()){let lastSync=0;try{const row:any=await env.DB.prepare("SELECT value FROM site_settings WHERE key='provider_catalog_last_sync'").first();lastSync=Number(row?.value||0)}catch{}const stale=!lastSync||Math.floor(Date.now()/1000)-lastSync>21600;if(stale){try{await syncProviderCatalog();const time=Math.floor(Date.now()/1000);await env.DB.prepare("INSERT INTO site_settings(key,value,updated_at) VALUES('provider_catalog_last_sync',?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").bind(String(time),time).run();q=await read()}catch(error){syncError=error instanceof Error?error.message:"Tedarikçi kataloğu güncellenemedi."}}}
 if(!q.results.length)return NextResponse.json({error:syncError||(!providerConfigured()?"PanelFollows API anahtarı Cloudflare ortamında tanımlı değil.":"Hizmet kataloğu boş döndü.")},{status:503});
 const newCutoff=Math.max(newServicesSince,Math.floor(Date.now()/1000)-7*86400);const rows=(q.results as any[]).map(row=>{let providerFeatures:any={},providerFields:any=[];try{providerFeatures=JSON.parse(row.providerFeatures||"{}")}catch{}try{providerFields=JSON.parse(row.providerFields||"[]")}catch{}return{...row,providerFeatures,providerFields,isNew:Number(row.createdAt)>=newCutoff}});
 return NextResponse.json(rows,{headers:{"x-catalog-sync":syncError?"stale":"ready","cache-control":"no-store, no-cache, must-revalidate, max-age=0","cdn-cache-control":"no-store"}});
}
export async function POST(r:Request){if(!await isAdmin())return NextResponse.json({error:"Yetkisiz işlem."},{status:403});const b=await r.json() as Input;if(!b.platform?.trim()||!b.category?.trim()||!b.name?.trim())return NextResponse.json({error:"Platform, kategori ve hizmet adı zorunlu."},{status:400});const x=await env.DB.prepare("INSERT INTO services(platform,category,name,provider_service_id,min_order,max_order,cost_price,sale_price,description,active,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) RETURNING id").bind(b.platform.trim(),b.category.trim(),b.name.trim(),b.providerServiceId?.trim()||"",Number(b.minOrder)||10,Number(b.maxOrder)||10000,cents(b.costPrice),cents(b.salePrice),b.description?.trim()||"",b.active===false?0:1,Math.floor(Date.now()/1000)).first();return NextResponse.json(x,{status:201})}
export async function PUT(r:Request){if(!await isAdmin())return NextResponse.json({error:"Yetkisiz işlem."},{status:403});const b=await r.json() as Input;if(!b.id)return NextResponse.json({error:"Hizmet bulunamadı."},{status:400});await env.DB.prepare("UPDATE services SET platform=?,category=?,name=?,provider_service_id=?,min_order=?,max_order=?,cost_price=?,sale_price=?,description=?,active=? WHERE id=?").bind(b.platform||"",b.category||"",b.name||"",b.providerServiceId||"",Number(b.minOrder)||10,Number(b.maxOrder)||10000,cents(b.costPrice),cents(b.salePrice),b.description||"",b.active===false?0:1,b.id).run();return NextResponse.json({ok:true})}
export async function DELETE(r:Request){if(!await isAdmin())return NextResponse.json({error:"Yetkisiz işlem."},{status:403});const id=Number(new URL(r.url).searchParams.get("id"));if(!id)return NextResponse.json({error:"Hizmet bulunamadı."},{status:400});await env.DB.prepare("DELETE FROM services WHERE id=?").bind(id).run();return NextResponse.json({ok:true})}
