"use client";
import { FormEvent,useEffect,useState } from "react";
export const extendedModules=["reports","dripfeed","subscriptions","cancel","subscribers","user-activity","blacklist-ip","blacklist-link","blacklist-email","blog-category","blog-posts","staffs","staff-activity","role-permissions","payment-bonuses","modules","news","languages","faqs","cronjobs"];
const definitions:Record<string,Array<[string,string,string?]>>={
 "blacklist-ip":[["value","IP adresi"],["reason","Neden"]],"blacklist-email":[["value","E-posta","email"],["reason","Neden"]],"blacklist-link":[["value","Alan adı veya tam bağlantı"],["reason","Neden"]],
 "blog-category":[["title","Kategori adı"],["slug","Adres (örnek: instagram)"]],"blog-posts":[["title","Yazı başlığı"],["slug","Adres (örnek: instagram-rehberi)"],["category","Kategori"],["body","Yazı","textarea"]],
 "role-permissions":[["title","Rol adı"]],"payment-bonuses":[["title","Bonus adı"],["minimum","En az ödeme (₺)","number"],["percent","Bonus (%)","number"]],"modules":[["name","Modül","module"]],"news":[["title","Duyuru başlığı"],["body","Duyuru metni","textarea"]],"languages":[["locale","Dil","locale"],["key","Metin anahtarı (services, search, account, popular...)"],["value","Yeni metin"]],"faqs":[["question","Soru"],["answer","Cevap","textarea"]],
 "staffs":[["name","Personel adı"],["username","Kullanıcı adı"],["role_id","Rol","role"],["password","Yeni personel şifresi (12+ karakter)","password"]],
};
const labels:Record<string,string>={overview:"İstatistikler",reports:"Raporlar",orders:"Siparişler",dripfeed:"Dripfeed",subscriptions:"Abonelikler",cancel:"İptal",services:"Hizmetler",finance:"İşlem kayıtları",support:"Destek",customers:"Müşteriler",subscribers:"Aboneler","user-activity":"Kullanıcı etkinliği","blacklist-ip":"IP kara listesi","blacklist-email":"E-posta kara listesi","blacklist-link":"Bağlantı kara listesi","blog-category":"Blog kategorileri","blog-posts":"Blog yazıları",staffs:"Personel","staff-activity":"Personel etkinliği","role-permissions":"Rol izinleri",settings:"Site ayarları",integration:"Tedarikçiler",payments:"Ödemeler","payment-bonuses":"Ödeme bonusları",modules:"Modüller",news:"Duyurular",languages:"Diller",faqs:"SSS",cronjobs:"Zamanlanmış işler",marketplace:"Pazaryeri",reviews:"Değerlendirmeler",music:"Müzik",api:"API"};
const input="w-full rounded-xl border border-white/10 bg-[#141820] px-3 py-3 text-sm text-white";
const date=(n:any)=>n?new Date(Number(n)*1000).toLocaleString("tr-TR",{timeZone:"Europe/Istanbul"}):"—";
const money=(n:any)=>(Number(n||0)/100).toLocaleString("tr-TR",{style:"currency",currency:"TRY"});
const states:Record<string,string>={active:"Aktif",paused:"Duraklatıldı",running:"Gönderiliyor",completed:"Tamamlandı",canceled:"İptal",failed:"Başarısız",needs_review:"Kontrol gerekli"};
export default function ModulePanel({module,canWrite}:{module:string;canWrite:boolean}){
 const [data,setData]=useState<any>(null),[form,setForm]=useState<any>({}),[id,setId]=useState<number|null>(null),[roles,setRoles]=useState<any[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[days,setDays]=useState("30"),[query,setQuery]=useState(""),[catalog,setCatalog]=useState<any[]>([]),[requestKey,setRequestKey]=useState(()=>crypto.randomUUID());
 const jobs=module==="dripfeed"||module==="subscriptions",fields=definitions[module]||[];
 async function load(){try{const r=await fetch(`/api/admin/modules?module=${module}&days=${days}`),d:any=await r.json();if(!r.ok)throw Error(d.error||"Bölüm yüklenemedi.");setData(d)}catch(e){setMessage(e instanceof Error?e.message:"Bölüm yüklenemedi.")}}
 useEffect(()=>{setData(null);setForm({});setId(null);setMessage("");setCatalog([]);setQuery("");load();if(module==="staffs")fetch('/api/admin/modules?module=role-permissions').then(r=>r.json()).then(d=>setRoles(Array.isArray(d)?d:[]))},[module,days]);
 async function action(action:string,record?:any,extra:any={}){setBusy(true);setMessage("");try{const r=await fetch('/api/admin/modules',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({module,action,id:record?.id,...extra})}),d:any=await r.json();if(!r.ok)throw Error(d.error||"İşlem tamamlanamadı.");setMessage("Kaydedildi.");await load();return true}catch(e){setMessage(e instanceof Error?e.message:"İşlem tamamlanamadı.");return false}finally{setBusy(false)}}
 async function save(e:FormEvent){e.preventDefault();if(jobs&&!confirm('Planın tüm tekrarlarının tutarı müşteri bakiyesinden ayrılacak. Siparişler 5 dakika sonra başlayacak. Plan oluşturulsun mu?'))return;const ok=await action('save',{id},{data:{...form,requestKey}});if(ok){setForm({});setId(null);setRequestKey(crypto.randomUUID())}}
 async function searchServices(){const r=await fetch(`/api/admin/modules?module=${module}&catalog=1&search=${encodeURIComponent(query)}`),d:any=await r.json();if(r.ok&&Array.isArray(d))setCatalog(d);else setMessage(d.error||"Hizmetler alınamadı.")}
 function csv(){const rows=data?.daily||[],text='Tarih,Sipariş,Satış,Kaydedilen maliyet,Tamamlanan\n'+rows.map((r:any)=>[r.date,r.orders,(r.revenue||0)/100,(r.cost||0)/100,r.completed].join(',')).join('\n'),a=document.createElement('a'),url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'}));a.href=url;a.download='elturco-rapor.csv';a.click();URL.revokeObjectURL(url)}
 const box="rounded-2xl border border-white/10 bg-[#0e1218] p-5";
 return <div className="space-y-5"><div className="flex items-center justify-between gap-3"><p className="text-sm text-zinc-400">{jobs?'Aynı bağlantıya aralıklı sipariş. Toplam ücret baştan ayrılır; gönderilmemiş tekrarlar iptal edilince iade edilir. Başlangıç ve çalıştırma aralığı en az 5 dakikadır.':module==='languages'?'Mevcut metin anahtarlarını altı dilde değiştirebilirsin.':module==='payment-bonuses'?'Bekleyen ödeme onaylanınca uygun en yüksek eşik uygulanır. Bonus yeniden onayda tekrar yazılmaz.':module==='news'?'Aktif duyuru müşteri vitrininde görünür.':module==='modules'?'Kapattığın sipariş ve plan modülleri yeni işlem kabul etmez.':module==='staffs'?'Önce Rol İzinleri bölümünden rol oluştur. Şifre yalnızca personel eklenirken kullanılır.':module==='cronjobs'?'Katalog ve Telegram kuyruğu otomatik çalışır; planlı siparişler yalnızca oluşturduğun aktif planlardan gönderilir.':module==='blog-posts'?'Aktif yazılar /blog adresinde yayınlanır.':''}</p><button onClick={load} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Yenile ↻</button></div>{message&&<p role="status" className="rounded-xl bg-orange-500/10 p-3 text-sm text-orange-300">{message}</p>}
 {module==='reports'&&<div className={box}><div className="mb-4 flex gap-3"><select value={days} onChange={e=>setDays(e.target.value)} className={input}>{[7,30,90,365].map(d=><option key={d} value={d}>Son {d} gün</option>)}</select><button onClick={csv} className="whitespace-nowrap rounded-xl bg-orange-600 px-4">CSV indir</button></div><p className="mb-4 text-xs text-zinc-500">Sipariş tutarı satış hacmidir. Maliyet, siparişte kayıtlı maliyettir; geçmişte maliyeti kaydedilmeyen siparişler gerçek kâr hesabına dahil edilemez.</p><Grid rows={data?.daily||[]} columns={['date','orders','revenue','cost','completed']} titles={['Tarih','Sipariş','Satış hacmi','Kayıtlı maliyet','Tamamlanan']} moneyFields={['revenue','cost']}/><h3 className="my-4 font-bold">Tedarikçiye göre</h3><Grid rows={data?.suppliers||[]} columns={['provider_id','orders','revenue','cost']} titles={['Tedarikçi','Sipariş','Satış hacmi','Kayıtlı maliyet']} moneyFields={['revenue','cost']}/></div>}
 {module==='cronjobs'&&<div className={box}><p>{data?.schedule}</p><p className="my-3 text-orange-300">{data?.telegramPending||0} Telegram duyurusu sırada</p><Grid rows={data?.runs||[]} columns={['key','updated_at']} titles={['İş','Son kayıt zamanı']} dateFields={['updated_at']}/>{canWrite&&<button disabled={busy} onClick={()=>action('run')} className="mt-4 rounded-xl bg-orange-600 px-5 py-3">Katalog kontrolü ve duyuru kuyruğunu çalıştır</button>}</div>}
 {(fields.length>0||jobs)&&canWrite&&<form onSubmit={save} className={box}><h3 className="mb-4 font-bold">{id?'Kaydı düzenle':jobs?'Yeni plan oluştur':'Yeni kayıt ekle'}</h3>{jobs&&<div className="mb-4"><div className="flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Hizmet adı ara" className={input}/><button type="button" onClick={searchServices} className="rounded-xl border border-white/10 px-4">Ara</button></div>{catalog.map(s=><button key={s.id} type="button" onClick={()=>setForm({...form,serviceId:s.id})} className="mt-2 block w-full rounded-xl bg-white/5 p-3 text-left text-xs">#{s.id} · {s.providerId} · {s.name} · {money(s.salePrice)} / {s.priceUnit==='per_order'?'sipariş':'1.000'}</button>)}</div>}
 <div className="grid gap-4 md:grid-cols-2">{(jobs?[["serviceId","ElTurco hizmet numarası","number"],["email","Müşteri e-postası","email"],["link","Hedef bağlantı","url"],["quantity","Her tekrarda adet","number"],["runs","Tekrar sayısı (2–100)","number"],["minutes","Aralık (dakika, en az 5)","number"]]:fields).map(([key,label,type])=><label key={key} className="text-xs text-zinc-400">{label}{type==='textarea'?<textarea required rows={5} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})} className={'mt-2 '+input}/>:['locale','role','module'].includes(type||'')?<select required value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})} className={'mt-2 '+input}><option value="">Seç</option>{type==='locale'?['tr','en','es','ru','pt','de'].map(x=><option key={x}>{x}</option>):type==='module'?['orders','dripfeed','subscriptions','blog','radio','api'].map(x=><option key={x} value={x}>{labels[x]||x}</option>):roles.filter(r=>r.active).map(r=><option key={r.id} value={r.id}>{r.data.title}</option>)}</select>:<input required={key!=='reason'&&key!=='category'&&!(id&&key==='password')} disabled={Boolean(id&&key==='password')} type={type||'text'} min={type==='number'?0:undefined} step={type==='number'?'any':undefined} value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})} className={'mt-2 '+input}/>}</label>)}</div>
 {module==='role-permissions'&&<div className="mt-5 grid gap-2 md:grid-cols-3">{Object.entries(labels).filter(([key])=>!['staffs','role-permissions'].includes(key)).map(([key,label])=><div key={key} className="rounded-xl border border-white/10 p-3 text-xs"><b>{label}</b>{['read','write'].map(mode=>{const permission=`${key}:${mode}`;return <label key={mode} className="mt-2 flex gap-2"><input type="checkbox" checked={(form.permissions||[]).includes(permission)} onChange={e=>setForm({...form,permissions:e.target.checked?[...(form.permissions||[]),permission]:(form.permissions||[]).filter((p:string)=>p!==permission)})}/>{mode==='read'?'Görüntüle':'Düzenle / işlem yap'}</label>})}</div>)}</div>}
 <div className="mt-4 flex gap-3"><button disabled={busy} className="rounded-xl bg-orange-600 px-5 py-3 font-bold disabled:opacity-40">{busy?'Kaydediliyor…':'Kaydet'}</button>{id&&<button type="button" onClick={()=>{setId(null);setForm({})}}>Vazgeç</button>}</div></form>}
 {module==='cancel'&&canWrite&&<form onSubmit={e=>{e.preventDefault();if(confirm('İptal isteği siparişin tedarikçisine gönderilsin mi?'))action('cancel',{id:Number(form.orderId)})}} className={box}><label>Sipariş numarası<input required type="number" min="1" value={form.orderId||''} onChange={e=>setForm({...form,orderId:e.target.value})} className={input}/></label><button disabled={busy} className="mt-3 rounded-xl bg-orange-600 px-5 py-3">Tedarikçiye iptal isteği gönder</button></form>}
 {Array.isArray(data)&&<div className={box}>{!data.length&&<p className="text-sm text-zinc-500">Henüz kayıt yok.</p>}{data.map((row:any)=><div key={row.id} className="border-b border-white/10 py-4"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0 flex-1"><b className="block break-words">{jobs?`#${row.id} · ${row.service_name}`:row.data?.title||row.data?.question||row.data?.value||row.data?.name||row.data?.locale||row.name||row.service_name||row.action}</b><p className="mt-2 whitespace-pre-wrap break-words text-xs leading-6 text-zinc-400">{jobs?`${row.customer_email} · ${row.quantity} adet × ${row.total_runs} · ${row.completed_runs} gönderim denendi\n${states[row.state]||row.state} · Sonraki: ${date(row.next_run_at)}\nToplam: ${money(row.unit_amount*row.total_runs)} · ${row.error||''}`:row.data?Object.entries(row.data).filter(([k])=>!['title','question','value','permissions'].includes(k)).map(([k,v])=>`${definitions[module]?.find(f=>f[0]===k)?.[1]||k}: ${v}`).join('\n'):Object.entries(row).filter(([k])=>!['id','name','role','service_name'].includes(k)).map(([k,v])=>`${({actor:'Kullanıcı',kind:'Tür',action:'İşlem',target:'Kayıt',created_at:'Zaman',email:'E-posta',username:'Kullanıcı adı',role_id:'Rol',active:'Aktif',provider_id:'Tedarikçi',provider_order_id:'Tedarikçi siparişi',provider_action:'İptal durumu',provider_error:'Yanıt',amount:'Tutar',status:'Durum',plan_count:'Plan sayısı'} as Record<string,string>)[k]||k}: ${k==='created_at'?date(v):k==='amount'?money(v):v}`).join(' · ')}</p>{row.data?.permissions&&<small className="text-zinc-500">{row.data.permissions.length} izin</small>}{row.active!==undefined&&<small className={row.active?'text-emerald-400':'text-zinc-500'}>{row.active?'● Aktif':'○ Pasif'}</small>}</div>
 {canWrite&&<div className="flex flex-wrap gap-3 text-xs">{jobs?<> {['active','paused'].includes(row.state)&&<button disabled={busy} onClick={()=>action(row.state==='active'?'pause':'resume',row)} className="text-orange-300">{row.state==='active'?'Duraklat':'Devam et'}</button>}{['active','paused','needs_review'].includes(row.state)&&<button disabled={busy} onClick={()=>{if(confirm('Gönderilmemiş tekrarlar iptal edilip ayrılan bakiye iade edilsin mi?'))action('cancel',row)}} className="text-red-300">İptal ve kalan tutarı iade</button>}</>:fields.length>0?<><button onClick={()=>{setId(row.id);setForm(row.data||{name:row.name,username:row.username,role_id:row.role_id});window.scrollTo({top:0,behavior:'smooth'})}} className="text-orange-300">Düzenle</button><button disabled={busy} onClick={()=>action('toggle',row,{active:!row.active})} className="text-zinc-300">{row.active?'Pasife al':'Aktifleştir'}</button></>:null}</div>}</div></div>)}</div>}</div>
}
function Grid({rows,columns,titles,moneyFields=[],dateFields=[]}:any){return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{titles.map((t:string)=><th key={t} className="p-3 text-xs text-zinc-500">{t}</th>)}</tr></thead><tbody>{rows.map((r:any,i:number)=><tr key={i} className="border-t border-white/10">{columns.map((c:string)=><td key={c} className="p-3">{moneyFields.includes(c)?money(r[c]):dateFields.includes(c)?date(r[c]):String(r[c]??'—')}</td>)}</tr>)}</tbody></table></div>}
