"use client";
import { useEffect,useState } from 'react';
export const languageOptions=[['tr','🇹🇷 TR · Türkçe'],['en','🇬🇧 EN · İngilizce'],['fr','🇫🇷 FR · Fransızca'],['uk','🇺🇦 UK · Ukraynaca'],['it','🇮🇹 IT · İtalyanca'],['ru','🇷🇺 RU · Rusça'],['de','🇩🇪 DE · Almanca'],['pt-BR','🇧🇷 BR · Brezilya Portekizcesi'],['es','🇪🇸 ES · İspanyolca']];
const input='w-full rounded-xl border border-white/10 bg-[#141820] px-3 py-3 text-sm text-white';
export default function Translations({canWrite}:{canWrite:boolean}){
 const [data,setData]=useState<any>(null),[search,setSearch]=useState(''),[form,setForm]=useState({locale:'en',source:'',translated:''}),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch('/api/admin/modules?module=languages&translations=1&search='+encodeURIComponent(search)),d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}catch{setNotice('Çeviri durumu alınamadı.')}}
 useEffect(()=>{void load()},[]);
 async function action(action:string){setBusy(true);setNotice('');try{const r=await fetch('/api/admin/modules',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({module:'languages',action,...form})}),d=await r.json();if(!r.ok)throw Error(d.error||'İşlem tamamlanamadı');setNotice(action==='translation-save'?'Çeviri kaydedildi. Yeni açılan sayfalarda uygulanır.':'Bekleyen çeviriler işlendi.');await load()}catch(e){setNotice(e instanceof Error?e.message:'Bağlantı kurulamadı')}finally{setBusy(false)}}
 return <section className="rounded-2xl border border-white/10 bg-[#0e1218] p-5"><h2 className="text-lg font-bold">Otomatik çeviri merkezi</h2><p className="mt-2 text-sm leading-6 text-zinc-400">Yeni hizmetler, açıklamalar ve ekran metinleri görüntülendiklerinde otomatik çevrilip saklanır. Çeviriyi burada düzeltirsen otomatik işlem üzerine yazmaz. Hizmet fiyatları ve tedarikçi bağlantıları değişmez.</p><div className="my-4 grid gap-3 sm:grid-cols-3">{languageOptions.map(([locale,label])=><div key={locale} className="rounded-xl border border-white/10 p-3 text-xs"><b>{label}</b><p className="mt-2 text-zinc-400">{data?.counts?.find((x:any)=>x.locale===locale)?.total||0} kayıt · {data?.queued?.find((x:any)=>x.locale===locale)?.total||0} bekleyen</p></div>)}</div><p className="text-xs text-zinc-500">Çeviri bağlantısı: {data?.configured?'Aktif':'Yapılandırma bekliyor'} · Bugünkü metin kotası: {Number(data?.characters||0).toLocaleString('tr-TR')} / {Number(data?.limit||250000).toLocaleString('tr-TR')} karakter. Kota dolunca kalan metinler sonraki güne bekler.</p>{canWrite&&<button disabled={busy} onClick={()=>action('translation-run')} className="mt-4 rounded-xl border border-orange-500/30 px-4 py-2 text-sm text-orange-300">Bekleyen çevirileri işle</button>}{notice&&<p role="status" className="mt-4 text-sm text-orange-300">{notice}</p>}
 {canWrite&&<form onSubmit={e=>{e.preventDefault();void action('translation-save')}} className="my-5 grid gap-3"><h3 className="font-bold">Metnin çevirisini düzelt</h3><label className="text-xs text-zinc-400">Dil<select className={'mt-2 '+input} value={form.locale} onChange={e=>setForm({...form,locale:e.target.value})}>{languageOptions.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label><div className="grid gap-3 md:grid-cols-2"><label className="text-xs text-zinc-400">Orijinal metin<textarea required rows={3} maxLength={3000} className={'mt-2 '+input} value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/></label><label className="text-xs text-zinc-400">Çevrilmiş metin<textarea required rows={3} maxLength={10000} className={'mt-2 '+input} value={form.translated} onChange={e=>setForm({...form,translated:e.target.value})}/></label></div><button disabled={busy} className="justify-self-start rounded-xl bg-orange-600 px-5 py-3 font-bold">Çeviriyi kaydet</button></form>}
 <form onSubmit={e=>{e.preventDefault();void load()}} className="mt-5 flex gap-2"><input aria-label="Çeviri ara" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Orijinal veya çevrilmiş metin ara…" className={input}/><button className="rounded-xl border border-white/10 px-4">Ara</button></form><div className="mt-4 space-y-3">{data?.rows?.map((row:any)=><article key={row.locale+row.source_hash} className="rounded-xl border border-white/10 p-3"><small className="text-orange-300">{languageOptions.find(x=>x[0]===row.locale)?.[1]} · {row.manual?'Elle düzeltilmiş':'Otomatik'}</small><p className="mt-2 whitespace-pre-wrap text-xs text-zinc-500">{row.source}</p><p className="mt-2 whitespace-pre-wrap text-sm text-zinc-200">{row.translated}</p>{canWrite&&<button onClick={()=>setForm({locale:row.locale,source:row.source,translated:row.translated})} className="mt-2 text-xs text-orange-300">Düzenle</button>}</article>)}</div></section>
}
