import { env } from "cloudflare:workers";
import { NextResponse } from "next/server";
import { isAdmin } from "@/lib/admin-auth";
import { forwardOrder,previewProviderOrder,providerConfigured } from "@/lib/provider";
import { fetchProviderBalance } from "@/lib/provider-catalog";
import { addCustomerNotification } from "@/lib/customer-notifications";
import { mailConfigured, sendTransactionalEmail } from "@/lib/mailer";
const now=()=>Math.floor(Date.now()/1000),cents=(v:unknown)=>Math.max(0,Math.round(Number(v||0)*100));
async function ensureReviews(){await env.DB.prepare("CREATE TABLE IF NOT EXISTS customer_reviews (id INTEGER PRIMARY KEY AUTOINCREMENT, customer_email TEXT NOT NULL UNIQUE, customer_name TEXT NOT NULL, rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5), title TEXT NOT NULL DEFAULT '', comment TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL)").run()}
export async function GET(r:Request){
 if(!await isAdmin())return NextResponse.json({error:"Yetkisiz"},{status:403});const view=new URL(r.url).searchParams.get("view")||"overview";
 if(view==="integration"){let providerBalance=null;if(providerConfigured())try{providerBalance=await fetchProviderBalance()}catch{}let telegramPendingCount=0;try{const pending:any=await env.DB.prepare("SELECT COUNT(*) total FROM site_settings WHERE key GLOB 'telegram_catalog_outbox:*'").first();telegramPendingCount=Number(pending?.total||0)}catch{}return NextResponse.json({providerConfigured:providerConfigured(),providerBalance,publicApiConfigured:Boolean((env as any).ELTURCO_API_KEY),shopierConfigured:Boolean((env as any).SHOPIER_ACCESS_TOKEN&&(env as any).SHOPIER_WEBHOOK_SECRET),shopierCheckoutConfigured:Boolean((env as any).SHOPIER_CHECKOUT_URL),emailConfigured:mailConfigured(),telegramConfigured:Boolean((env as any).TELEGRAM_BOT_TOKEN),telegramTarget:String((env as any).TELEGRAM_CHAT_ID||"@ElTurcoSmm"),telegramPendingCount,providerUrl:providerConfigured()?new URL(String((env as any).SMM_PROVIDER_API_URL)).origin:""})}
 if(view==="marketplace-orders"){try{const q=await env.DB.prepare("SELECT id,customer_name,service_name,link,quantity,amount,status,provider_order_id,provider_error,provider_cost,external_sale_amount,external_reference,created_at FROM orders WHERE source='marketplace' ORDER BY id DESC LIMIT 100").all();return NextResponse.json(q.results)}catch{return NextResponse.json({error:"Pazaryeri sipariş tablosu güncellemesi henüz uygulanmamış."},{status:503})}}
 if(view==="settings"){const q=await env.DB.prepare("SELECT key,value FROM site_settings").all();return NextResponse.json(Object.fromEntries((q.results as any[]).map(x=>[x.key,x.value])))}
 if(view==="music"){const q=await env.DB.prepare("SELECT * FROM music_tracks ORDER BY position ASC,id ASC").all();return NextResponse.json(q.results)}
 if(view==="overview"){
  const [money,orders,support,payments,customers,services,recentOrders,topServices]=await env.DB.batch([
   env.DB.prepare("SELECT COALESCE(SUM(CASE WHEN type='income' THEN amount ELSE -amount END),0) balance,COALESCE(SUM(CASE WHEN type='income' THEN amount ELSE 0 END),0) income,COALESCE(SUM(CASE WHEN type='expense' THEN amount ELSE 0 END),0) expense FROM transactions WHERE status='completed'"),
   env.DB.prepare("SELECT COUNT(*) total,SUM(CASE WHEN status='pending' THEN 1 ELSE 0 END) pending,SUM(CASE WHEN status='processing' THEN 1 ELSE 0 END) processing,SUM(CASE WHEN status='completed' THEN 1 ELSE 0 END) completed,COALESCE(SUM(amount),0) volume FROM orders"),
   env.DB.prepare("SELECT COUNT(*) total,SUM(CASE WHEN status='open' THEN 1 ELSE 0 END) open FROM support_threads"),
   env.DB.prepare("SELECT COUNT(*) total,SUM(CASE WHEN status='pending' THEN 1 ELSE 0 END) pending FROM payment_requests"),
   env.DB.prepare("SELECT COUNT(*) total FROM customer_users"),
   env.DB.prepare("SELECT COUNT(*) total,SUM(CASE WHEN active=1 THEN 1 ELSE 0 END) active FROM services"),
   env.DB.prepare("SELECT id,customer_name,service_name,amount,status,created_at FROM orders ORDER BY id DESC LIMIT 6"),
   env.DB.prepare("SELECT service_name,COUNT(*) orders,COALESCE(SUM(quantity),0) quantity,COALESCE(SUM(amount),0) revenue FROM orders GROUP BY service_name ORDER BY orders DESC,revenue DESC LIMIT 5")
  ]);
  let providerBalance=null;if(providerConfigured())try{providerBalance=await fetchProviderBalance()}catch{}
  return NextResponse.json({money:money.results[0],orders:orders.results[0],support:support.results[0],payments:payments.results[0],customers:customers.results[0],services:services.results[0],recentOrders:recentOrders.results,topServices:topServices.results,systems:{provider:providerConfigured(),providerBalance,email:mailConfigured(),shopier:Boolean((env as any).SHOPIER_ACCESS_TOKEN&&(env as any).SHOPIER_WEBHOOK_SECRET),telegram:Boolean((env as any).TELEGRAM_BOT_TOKEN)}})
 }
 if(view==="customers"){const q=await env.DB.prepare("SELECT u.id,u.name,u.email,u.created_at,COALESCE(b.balance,0) balance,(SELECT COUNT(*) FROM orders o WHERE o.customer_name=u.name) order_count FROM customer_users u LEFT JOIN customer_balances b ON b.email=u.email ORDER BY u.id DESC LIMIT 300").all();return NextResponse.json(q.results)}
 if(view==="reviews"){await ensureReviews();const q=await env.DB.prepare("SELECT * FROM customer_reviews ORDER BY id DESC LIMIT 300").all();return NextResponse.json(q.results)}
 const tables:any={transactions:"transactions",payments:"payment_requests",methods:"payment_methods",orders:"orders",support:"support_threads"},table=tables[view];if(!table)return NextResponse.json([]);const q=await env.DB.prepare(`SELECT * FROM ${table} ORDER BY id DESC LIMIT 200`).all();if(view==="support"){for(const t of q.results as any[]){const m=await env.DB.prepare("SELECT * FROM support_messages WHERE thread_id=? ORDER BY id ASC").bind(t.id).all();t.messages=m.results}}return NextResponse.json(q.results)
}
export async function POST(r:Request){
 if(!await isAdmin())return NextResponse.json({error:"Yetkisiz"},{status:403});const b=await r.json() as any;
 if(b.action==="smtp-test"){
  const recipient=String((env as any).SMTP_USER||"elturcosmm@gmail.com").trim();
  const result=await sendTransactionalEmail({to:recipient,subject:"ElTurco SMM e-posta testi",text:"ElTurco SMM e-posta gönderimi başarıyla çalışıyor."});
  return NextResponse.json(result,result.sent?{status:200}:{status:502});
 }
 if(b.action==="marketplace-order"){
  if(!providerConfigured())return NextResponse.json({error:"PanelFollows API ayarı yapılmamış."},{status:503});
  const serviceId=Number(b.serviceId),quantity=Math.floor(Number(b.quantity)),link=String(b.link||"").trim(),buyer=String(b.buyerName||"").trim().slice(0,120),reference=String(b.externalReference||"").trim().slice(0,160),saleAmount=cents(b.saleAmount);
  if(!serviceId||!quantity||!link||!buyer||!reference)return NextResponse.json({error:"Hizmet, müşteri adı, pazaryeri sipariş numarası, hedef link ve geçerli adet gerekli."},{status:400});
  const service:any=await env.DB.prepare("SELECT id,name,provider_service_id,min_order,max_order,cost_price,sale_price,price_unit,provider_fields,active FROM services WHERE id=?").bind(serviceId).first();
  if(!service||!service.active)return NextResponse.json({error:"Hizmet aktif değil veya bulunamadı."},{status:404});
  if(!service.provider_service_id)return NextResponse.json({error:"Bu hizmetin tedarikçi servis ID'si bağlı değil."},{status:400});
  if(quantity<Number(service.min_order)||quantity>Number(service.max_order))return NextResponse.json({error:`Adet ${service.min_order}–${service.max_order} arasında olmalı.`},{status:400});
  const cost=service.price_unit==="per_order"?Number(service.cost_price):Math.ceil(Number(service.cost_price)*quantity/1000);
  let allowed:any[]=[];try{allowed=JSON.parse(service.provider_fields||"[]")}catch{}
  const submitted=b.fields&&typeof b.fields==="object"&&!Array.isArray(b.fields)?b.fields:{},fields:Record<string,string>={};
  for(const field of allowed){
    const name=String(field?.name||"");if(!/^[a-z][a-z0-9_]{0,39}$/i.test(name)||["link","quantity","service"].includes(name))continue;
    const raw=submitted[name]??field.default??"";
    const value=String(raw).trim();
    if(field.required!==false&&!value)return NextResponse.json({error:`${field.label||name} alanı zorunlu. ${field.description||""}`.trim()},{status:400});
    if(value.length>10000)return NextResponse.json({error:`${field.label||name} alanı çok uzun.`},{status:400});
    if(value)fields[name]=value;
  }
  const order={service:String(service.provider_service_id),link,quantity,fields},preview=await previewProviderOrder(order);
  if(!preview.ok)return NextResponse.json({error:preview.error||"Tedarikçi bu sipariş bilgilerini kabul etmedi."},{status:preview.status===0||preview.status>=500?502:400});
  const created:any=await env.DB.prepare("INSERT INTO orders(customer_name,customer_email,service_name,service_id,provider_service_id,link,quantity,amount,status,created_at,source,external_reference,external_sale_amount,provider_cost) VALUES(?,?,?,?,?,?,?,?,? ,?,'marketplace',?,?,?) RETURNING id").bind(buyer,"",service.name,service.id,service.provider_service_id,link,quantity,saleAmount,"pending",now(),reference,saleAmount,cost).first();
  const requestKey=`elturco-marketplace-${created.id}`,result=await forwardOrder({...order,idempotencyKey:requestKey});
  if(!result.forwarded&&!result.uncertain){await env.DB.prepare("UPDATE orders SET status='failed',provider_error=? WHERE id=?").bind(result.error||"Tedarikçi siparişi kabul etmedi.",created.id).run();return NextResponse.json({error:result.error||"Tedarikçi siparişi kabul etmedi.",id:created.id},{status:502})}
  await env.DB.prepare("UPDATE orders SET provider_order_id=?,provider_error=?,status=?,provider_synced_at=? WHERE id=?").bind(result.providerOrderId||"",result.error||"",result.forwarded?"processing":"pending",now(),created.id).run();
  await env.DB.prepare("INSERT INTO transactions(type,amount,category,description,status,created_at) VALUES('expense',?,'Pazaryeri tedarikçi maliyeti',?,'completed',?)").bind(cost,`#${created.id} · ${reference||"Dış satış"} · ${service.name}`,now()).run();
  return NextResponse.json({ok:true,id:created.id,providerOrderId:result.providerOrderId||"bekleniyor",status:result.forwarded?"processing":"pending",cost},{status:201})
}
 else if(b.action==="transaction")await env.DB.prepare("INSERT INTO transactions(type,amount,category,description,status,created_at) VALUES(?,?,?,?,?,?)").bind(b.type,cents(b.amount),b.category,b.description||"","completed",now()).run();
 else if(b.action==="method")await env.DB.prepare("INSERT INTO payment_methods(name,type,instructions,active,created_at) VALUES(?,?,?,?,?)").bind(b.name,b.type,b.instructions||"",1,now()).run();
 else if(b.action==="method-update")await env.DB.prepare("UPDATE payment_methods SET name=?,type=?,instructions=?,active=? WHERE id=?").bind(String(b.name||"").trim(),String(b.type||""),String(b.instructions||"").trim(),b.active===false?0:1,Number(b.id)).run();
 else if(b.action==="settings"){const allowed=["brand_name","panel_label","hero_title","hero_text","announcement","support_title","support_text","system_label","payment_title","payment_text","radio_title","show_radio","show_api","show_support","welcome_theme"];const entries=Object.entries(b.values||{}).filter(([k])=>allowed.includes(k));await env.DB.batch(entries.map(([k,v])=>env.DB.prepare("INSERT INTO site_settings(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").bind(k,String(v??""),now())))}
 else if(b.action==="publish-announcement"){const translations:any={};for(const locale of ["tr","en","es","ru","pt","de"]){const item=b.translations?.[locale];if(!item)continue;const title=String(item.title||"").trim().slice(0,120),body=String(item.body||"").trim().slice(0,800);if(title&&body)translations[locale]={title,body}}const fallback=translations.tr||Object.values(translations)[0] as any;if(!fallback)return NextResponse.json({error:"En az bir dilde başlık ve duyuru metni gerekli."},{status:400});const createdAt=now(),serialized=JSON.stringify(translations);const count:any=await env.DB.prepare("SELECT COUNT(*) total FROM customer_users").first();await env.DB.prepare("INSERT INTO customer_notifications(customer_email,kind,title,body,translations,created_at) SELECT email,'announcement',?,?,?,? FROM customer_users").bind(fallback.title,fallback.body,serialized,createdAt).run();return NextResponse.json({ok:true,deliveredTo:Number(count?.total||0)})}
 else if(b.action==="customer-balance"){const email=String(b.email||"").trim().toLowerCase(),amount=Math.round(Number(b.amount||0)*100);if(!email||!Number.isFinite(amount)||amount===0)return NextResponse.json({error:"Geçerli müşteri ve sıfırdan farklı tutar gerekli."},{status:400});const customer:any=await env.DB.prepare("SELECT name FROM customer_users WHERE email=?").bind(email).first();if(!customer)return NextResponse.json({error:"Müşteri bulunamadı."},{status:404});const current:any=await env.DB.prepare("SELECT COALESCE(balance,0) balance FROM customer_balances WHERE email=?").bind(email).first();if(Number(current?.balance||0)+amount<0)return NextResponse.json({error:"Bakiye eksiye düşemez."},{status:400});const time=now();await env.DB.batch([env.DB.prepare("INSERT INTO customer_balances(email,balance,created_at,updated_at) VALUES(?,?,?,?) ON CONFLICT(email) DO UPDATE SET balance=balance+excluded.balance,updated_at=excluded.updated_at").bind(email,amount,time,time),env.DB.prepare("INSERT INTO transactions(type,amount,category,description,status,created_at) VALUES(?,?,?,?,?,?)").bind(amount>0?"income":"expense",Math.abs(amount),"Admin bakiye düzenlemesi",customer.name+" · "+email,"completed",time)])}
 else if(b.action==="review-status"){await ensureReviews();await env.DB.prepare("UPDATE customer_reviews SET active=? WHERE id=?").bind(b.active?1:0,Number(b.id)).run()}
 else if(b.action==="music-save"){if(!String(b.title||"").trim()||!String(b.src||"").trim())return NextResponse.json({error:"Şarkı adı ve dosya yolu zorunlu."},{status:400});if(b.id)await env.DB.prepare("UPDATE music_tracks SET title=?,artist=?,src=?,position=?,active=? WHERE id=?").bind(String(b.title).trim(),String(b.artist||"").trim(),String(b.src).trim(),Number(b.position)||0,b.active===false?0:1,Number(b.id)).run();else await env.DB.prepare("INSERT INTO music_tracks(title,artist,src,position,active,created_at) VALUES(?,?,?,?,?,?)").bind(String(b.title).trim(),String(b.artist||"").trim(),String(b.src).trim(),Number(b.position)||0,b.active===false?0:1,now()).run()}
 else if(b.action==="status"){const allowed:any={order:"orders",payment:"payment_requests",support:"support_threads"},table=allowed[b.target];if(!table)return NextResponse.json({error:"Geçersiz işlem"},{status:400});const previous:any=b.target==="payment"?await env.DB.prepare("SELECT status,amount,customer_name,email FROM payment_requests WHERE id=?").bind(b.id).first():b.target==="order"?await env.DB.prepare("SELECT status,customer_email customerEmail,service_name serviceName FROM orders WHERE id=? AND customer_email<>''").bind(b.id).first():null;await env.DB.prepare(`UPDATE ${table} SET status=? WHERE id=?`).bind(b.status,b.id).run();if(b.target==="payment"&&previous&&previous.status!==b.status){const email=String(previous.email||"").trim().toLowerCase();if(b.status==="approved"){const time=now();await env.DB.batch([env.DB.prepare("INSERT INTO transactions(type,amount,category,description,status,created_at) VALUES('income',?,'Bakiye yükleme',?,'completed',?)").bind(previous.amount,"Ödeme #"+b.id+" · "+previous.customer_name,time),env.DB.prepare("INSERT INTO customer_balances(email,balance,created_at,updated_at) VALUES(?,?,?,?) ON CONFLICT(email) DO UPDATE SET balance=balance+excluded.balance,updated_at=excluded.updated_at").bind(email,previous.amount,time,time)]);if(email)await addCustomerNotification({email,kind:"balance",title:"Bakiye yüklemen onaylandı",body:`₺${(Number(previous.amount)/100).toFixed(2)} hesabına eklendi.`,emailSubject:"ElTurco SMM · Bakiye yüklemen onaylandı"})}else if(b.status==="rejected"&&email)await addCustomerNotification({email,kind:"balance",title:"Bakiye yükleme talebin reddedildi",body:`Ödeme talebi #${b.id} onaylanmadı. Ayrıntı için destek ekibine ulaşabilirsin.`,emailSubject:"ElTurco SMM · Bakiye talebi hakkında"})}if(b.target==="order"&&previous&&previous.status!==b.status&&previous.customerEmail)await addCustomerNotification({email:String(previous.customerEmail),kind:"order",orderId:Number(b.id),title:`Sipariş #${b.id} durumu güncellendi`,body:`${previous.serviceName}: ${String(b.status).slice(0,40)}.`,emailSubject:`ElTurco SMM · Sipariş #${b.id} güncellendi`})}
 else if(b.action==="retry-order"){const o:any=await env.DB.prepare("SELECT provider_service_id,link,quantity FROM orders WHERE id=?").bind(b.id).first();if(!o)return NextResponse.json({error:"Sipariş bulunamadı"},{status:404});if(!o.provider_service_id)return NextResponse.json({error:"Tedarikçi servis ID eksik"},{status:400});const result=await forwardOrder({service:o.provider_service_id,link:o.link,quantity:o.quantity});await env.DB.prepare("UPDATE orders SET provider_order_id=?,provider_error=?,status=? WHERE id=?").bind(result.providerOrderId||"",result.error||"",result.forwarded?"processing":"pending",b.id).run();if(!result.forwarded)return NextResponse.json({error:result.error},{status:502})}
 else if(b.action==="reply"){await env.DB.prepare("INSERT INTO support_messages(thread_id,sender,message,created_at) VALUES(?,'admin',?,?)").bind(b.threadId,b.message,now()).run();await env.DB.prepare("UPDATE support_threads SET updated_at=? WHERE id=?").bind(now(),b.threadId).run()}
 else return NextResponse.json({error:"Geçersiz işlem"},{status:400});return NextResponse.json({ok:true})
}
export async function DELETE(r:Request){if(!await isAdmin())return NextResponse.json({error:"Yetkisiz"},{status:403});const u=new URL(r.url),kind=u.searchParams.get("kind"),id=Number(u.searchParams.get("id"));const allowed:any={transaction:"transactions",method:"payment_methods",music:"music_tracks",review:"customer_reviews"};if(!allowed[kind]||!id)return NextResponse.json({error:"Geçersiz"},{status:400});if(kind==="review")await ensureReviews();await env.DB.prepare(`DELETE FROM ${allowed[kind]} WHERE id=?`).bind(id).run();return NextResponse.json({ok:true})}
