import { env } from "cloudflare:workers";
import { NextResponse } from "next/server";
import { isAdmin } from "@/lib/admin-auth";
import { forwardOrder,providerConfigured } from "@/lib/provider";
import { fetchProviderBalance } from "@/lib/provider-catalog";
const now=()=>Math.floor(Date.now()/1000),cents=(v:unknown)=>Math.max(0,Math.round(Number(v||0)*100));
export async function GET(r:Request){
 if(!await isAdmin())return NextResponse.json({error:"Yetkisiz"},{status:403});const view=new URL(r.url).searchParams.get("view")||"overview";
 if(view==="integration"){let providerBalance=null;if(providerConfigured())try{providerBalance=await fetchProviderBalance()}catch{}return NextResponse.json({providerConfigured:providerConfigured(),providerBalance,publicApiConfigured:Boolean((env as any).KIVIL_API_KEY),shopierConfigured:Boolean((env as any).SHOPIER_ACCESS_TOKEN&&(env as any).SHOPIER_WEBHOOK_SECRET),shopierCheckoutConfigured:Boolean((env as any).SHOPIER_CHECKOUT_URL),providerUrl:providerConfigured()?new URL(String((env as any).SMM_PROVIDER_API_URL)).origin:""})}
 if(view==="settings"){const q=await env.DB.prepare("SELECT key,value FROM site_settings").all();return NextResponse.json(Object.fromEntries((q.results as any[]).map(x=>[x.key,x.value])))}
 if(view==="music"){const q=await env.DB.prepare("SELECT * FROM music_tracks ORDER BY position ASC,id ASC").all();return NextResponse.json(q.results)}
 if(view==="overview"){const [money,orders,support,payments]=await env.DB.batch([env.DB.prepare("SELECT COALESCE(SUM(CASE WHEN type='income' THEN amount ELSE -amount END),0) balance,COALESCE(SUM(CASE WHEN type='income' THEN amount ELSE 0 END),0) income,COALESCE(SUM(CASE WHEN type='expense' THEN amount ELSE 0 END),0) expense FROM transactions WHERE status='completed'"),env.DB.prepare("SELECT COUNT(*) total,SUM(CASE WHEN status='pending' THEN 1 ELSE 0 END) pending FROM orders"),env.DB.prepare("SELECT COUNT(*) total,SUM(CASE WHEN status='open' THEN 1 ELSE 0 END) open FROM support_threads"),env.DB.prepare("SELECT COUNT(*) total,SUM(CASE WHEN status='pending' THEN 1 ELSE 0 END) pending FROM payment_requests")]);return NextResponse.json({money:money.results[0],orders:orders.results[0],support:support.results[0],payments:payments.results[0]})}
 const tables:any={transactions:"transactions",payments:"payment_requests",methods:"payment_methods",orders:"orders",support:"support_threads"},table=tables[view];if(!table)return NextResponse.json([]);const q=await env.DB.prepare(`SELECT * FROM ${table} ORDER BY id DESC LIMIT 200`).all();if(view==="support"){for(const t of q.results as any[]){const m=await env.DB.prepare("SELECT * FROM support_messages WHERE thread_id=? ORDER BY id ASC").bind(t.id).all();t.messages=m.results}}return NextResponse.json(q.results)
}
export async function POST(r:Request){
 if(!await isAdmin())return NextResponse.json({error:"Yetkisiz"},{status:403});const b=await r.json() as any;
 if(b.action==="transaction")await env.DB.prepare("INSERT INTO transactions(type,amount,category,description,status,created_at) VALUES(?,?,?,?,?,?)").bind(b.type,cents(b.amount),b.category,b.description||"","completed",now()).run();
 else if(b.action==="method")await env.DB.prepare("INSERT INTO payment_methods(name,type,instructions,active,created_at) VALUES(?,?,?,?,?)").bind(b.name,b.type,b.instructions||"",1,now()).run();
 else if(b.action==="method-update")await env.DB.prepare("UPDATE payment_methods SET name=?,type=?,instructions=?,active=? WHERE id=?").bind(String(b.name||"").trim(),String(b.type||""),String(b.instructions||"").trim(),b.active===false?0:1,Number(b.id)).run();
 else if(b.action==="settings"){const allowed=["brand_name","panel_label","hero_title","hero_text","announcement","support_title","support_text","system_label","payment_title","payment_text","radio_title","show_radio","show_api","show_support"];const entries=Object.entries(b.values||{}).filter(([k])=>allowed.includes(k));await env.DB.batch(entries.map(([k,v])=>env.DB.prepare("INSERT INTO site_settings(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").bind(k,String(v??""),now())))}
 else if(b.action==="music-save"){if(!String(b.title||"").trim()||!String(b.src||"").trim())return NextResponse.json({error:"Şarkı adı ve dosya yolu zorunlu."},{status:400});if(b.id)await env.DB.prepare("UPDATE music_tracks SET title=?,artist=?,src=?,position=?,active=? WHERE id=?").bind(String(b.title).trim(),String(b.artist||"").trim(),String(b.src).trim(),Number(b.position)||0,b.active===false?0:1,Number(b.id)).run();else await env.DB.prepare("INSERT INTO music_tracks(title,artist,src,position,active,created_at) VALUES(?,?,?,?,?,?)").bind(String(b.title).trim(),String(b.artist||"").trim(),String(b.src).trim(),Number(b.position)||0,b.active===false?0:1,now()).run()}
 else if(b.action==="status"){const allowed:any={order:"orders",payment:"payment_requests",support:"support_threads"},table=allowed[b.target];if(!table)return NextResponse.json({error:"Geçersiz işlem"},{status:400});await env.DB.prepare(`UPDATE ${table} SET status=? WHERE id=?`).bind(b.status,b.id).run();if(b.target==="payment"&&b.status==="approved"){const p:any=await env.DB.prepare("SELECT amount,customer_name FROM payment_requests WHERE id=?").bind(b.id).first();if(p)await env.DB.prepare("INSERT INTO transactions(type,amount,category,description,status,created_at) VALUES('income',?,'Bakiye yükleme',?,'completed',?)").bind(p.amount,"Ödeme #"+b.id+" · "+p.customer_name,now()).run()}}
 else if(b.action==="retry-order"){const o:any=await env.DB.prepare("SELECT provider_service_id,link,quantity FROM orders WHERE id=?").bind(b.id).first();if(!o)return NextResponse.json({error:"Sipariş bulunamadı"},{status:404});if(!o.provider_service_id)return NextResponse.json({error:"Tedarikçi servis ID eksik"},{status:400});const result=await forwardOrder({service:o.provider_service_id,link:o.link,quantity:o.quantity});await env.DB.prepare("UPDATE orders SET provider_order_id=?,provider_error=?,status=? WHERE id=?").bind(result.providerOrderId||"",result.error||"",result.forwarded?"processing":"pending",b.id).run();if(!result.forwarded)return NextResponse.json({error:result.error},{status:502})}
 else if(b.action==="reply"){await env.DB.prepare("INSERT INTO support_messages(thread_id,sender,message,created_at) VALUES(?,'admin',?,?)").bind(b.threadId,b.message,now()).run();await env.DB.prepare("UPDATE support_threads SET updated_at=? WHERE id=?").bind(now(),b.threadId).run()}
 else return NextResponse.json({error:"Geçersiz işlem"},{status:400});return NextResponse.json({ok:true})
}
export async function DELETE(r:Request){if(!await isAdmin())return NextResponse.json({error:"Yetkisiz"},{status:403});const u=new URL(r.url),kind=u.searchParams.get("kind"),id=Number(u.searchParams.get("id"));const allowed:any={transaction:"transactions",method:"payment_methods",music:"music_tracks"};if(!allowed[kind]||!id)return NextResponse.json({error:"Geçersiz"},{status:400});await env.DB.prepare(`DELETE FROM ${allowed[kind]} WHERE id=?`).bind(id).run();return NextResponse.json({ok:true})}
