import { env } from "cloudflare:workers";
import { NextResponse } from "next/server";
import { isAdmin } from "@/lib/admin-auth";
import { forwardOrder,providerConfigured } from "@/lib/provider";
import { fetchProviderBalance } from "@/lib/provider-catalog";
const now=()=>Math.floor(Date.now()/1000),cents=(v:unknown)=>Math.max(0,Math.round(Number(v||0)*100));
async function ensureReviews(){await env.DB.prepare("CREATE TABLE IF NOT EXISTS customer_reviews (id INTEGER PRIMARY KEY AUTOINCREMENT, customer_email TEXT NOT NULL UNIQUE, customer_name TEXT NOT NULL, rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5), title TEXT NOT NULL DEFAULT '', comment TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL)").run()}
export async function GET(r:Request){
 if(!await isAdmin())return NextResponse.json({error:"Yetkisiz"},{status:403});const view=new URL(r.url).searchParams.get("view")||"overview";
 if(view==="integration"){let providerBalance=null;if(providerConfigured())try{providerBalance=await fetchProviderBalance()}catch{}const shopierConfigured=Boolean((env as any).SHOPIER_API_KEY&&(env as any).SHOPIER_API_SECRET&&(env as any).SHOPIER_ACCESS_TOKEN);return NextResponse.json({providerConfigured:providerConfigured(),providerBalance,publicApiConfigured:Boolean((env as any).ELTURCO_API_KEY),shopierConfigured,shopierCheckoutConfigured:shopierConfigured,shopierCallbackConfigured:Boolean((env as any).SHOPIER_CALLBACK_URL),providerUrl:providerConfigured()?new URL(String((env as any).SMM_PROVIDER_API_URL)).origin:""})}
 if(view==="settings"){const q=await env.DB.prepare("SELECT key,value FROM site_settings").all();return NextResponse.json(Object.fromEntries((q.results as any[]).map(x=>[x.key,x.value])))}
 if(view==="music"){const q=await env.DB.prepare("SELECT * FROM music_tracks ORDER BY position ASC,id ASC").all();return NextResponse.json(q.results)}
 if(view==="overview"){const [money,orders,support,payments]=await env.DB.batch([env.DB.prepare("SELECT COALESCE(SUM(CASE WHEN type='income' THEN amount ELSE -amount END),0) balance,COALESCE(SUM(CASE WHEN type='income' THEN amount ELSE 0 END),0) income,COALESCE(SUM(CASE WHEN type='expense' THEN amount ELSE 0 END),0) expense FROM transactions WHERE status='completed'"),env.DB.prepare("SELECT COUNT(*) total,SUM(CASE WHEN status='pending' THEN 1 ELSE 0 END) pending FROM orders"),env.DB.prepare("SELECT COUNT(*) total,SUM(CASE WHEN status='open' THEN 1 ELSE 0 END) open FROM support_threads"),env.DB.prepare("SELECT COUNT(*) total,SUM(CASE WHEN status='pending' THEN 1 ELSE 0 END) pending FROM payment_requests")]);return NextResponse.json({money:money.results[0],orders:orders.results[0],support:support.results[0],payments:payments.results[0]})}
 if(view==="customers"){const q=await env.DB.prepare("SELECT u.id,u.name,u.email,u.created_at,COALESCE(b.balance,0) balance,(SELECT COUNT(*) FROM orders o WHERE o.customer_name=u.name) order_count FROM customer_users u LEFT JOIN customer_balances b ON b.email=u.email ORDER BY u.id DESC LIMIT 300").all();return NextResponse.json(q.results)}
 if(view==="reviews"){await ensureReviews();const q=await env.DB.prepare("SELECT * FROM customer_reviews ORDER BY id DESC LIMIT 300").all();return NextResponse.json(q.results)}
 const tables:any={transactions:"transactions",payments:"payment_requests",methods:"payment_methods",orders:"orders",support:"support_threads"},table=tables[view];if(!table)return NextResponse.json([]);const q=await env.DB.prepare(`SELECT * FROM ${table} ORDER BY id DESC LIMIT 200`).all();if(view==="support"){for(const t of q.results as any[]){const m=await env.DB.prepare("SELECT * FROM support_messages WHERE thread_id=? ORDER BY id ASC").bind(t.id).all();t.messages=m.results}}return NextResponse.json(q.results)
}
export async function POST(r:Request){
 if(!await isAdmin())return NextResponse.json({error:"Yetkisiz"},{status:403});const b=await r.json() as any;
 if(b.action==="transaction")await env.DB.prepare("INSERT INTO transactions(type,amount,category,description,status,created_at) VALUES(?,?,?,?,?,?)").bind(b.type,cents(b.amount),b.category,b.description||"","completed",now()).run();
 else if(b.action==="method")await env.DB.prepare("INSERT INTO payment_methods(name,type,instructions,active,created_at) VALUES(?,?,?,?,?)").bind(b.name,b.type,b.instructions||"",1,now()).run();
 else if(b.action==="method-update")await env.DB.prepare("UPDATE payment_methods SET name=?,type=?,instructions=?,active=? WHERE id=?").bind(String(b.name||"").trim(),String(b.type||""),String(b.instructions||"").trim(),b.active===false?0:1,Number(b.id)).run();
 else if(b.action==="settings"){const allowed=["brand_name","panel_label","hero_title","hero_text","announcement","support_title","support_text","system_label","payment_title","payment_text","radio_title","show_radio","show_api","show_support"];const entries=Object.entries(b.values||{}).filter(([k])=>allowed.includes(k));await env.DB.batch(entries.map(([k,v])=>env.DB.prepare("INSERT INTO site_settings(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").bind(k,String(v??""),now())))}
 else if(b.action==="customer-balance"){const email=String(b.email||"").trim().toLowerCase(),amount=Math.round(Number(b.amount||0)*100);if(!email||!Number.isFinite(amount)||amount===0)return NextResponse.json({error:"Geçerli müşteri ve sıfırdan farklı tutar gerekli."},{status:400});const customer:any=await env.DB.prepare("SELECT name FROM customer_users WHERE email=?").bind(email).first();if(!customer)return NextResponse.json({error:"Müşteri bulunamadı."},{status:404});const current:any=await env.DB.prepare("SELECT COALESCE(balance,0) balance FROM customer_balances WHERE email=?").bind(email).first();if(Number(current?.balance||0)+amount<0)return NextResponse.json({error:"Bakiye eksiye düşemez."},{status:400});const time=now();await env.DB.batch([env.DB.prepare("INSERT INTO customer_balances(email,balance,created_at,updated_at) VALUES(?,?,?,?) ON CONFLICT(email) DO UPDATE SET balance=balance+excluded.balance,updated_at=excluded.updated_at").bind(email,amount,time,time),env.DB.prepare("INSERT INTO transactions(type,amount,category,description,status,created_at) VALUES(?,?,?,?,?,?)").bind(amount>0?"income":"expense",Math.abs(amount),"Admin bakiye düzenlemesi",customer.name+" · "+email,"completed",time)])}
 else if(b.action==="review-status"){await ensureReviews();await env.DB.prepare("UPDATE customer_reviews SET active=? WHERE id=?").bind(b.active?1:0,Number(b.id)).run()}
 else if(b.action==="music-save"){if(!String(b.title||"").trim()||!String(b.src||"").trim())return NextResponse.json({error:"Şarkı adı ve dosya yolu zorunlu."},{status:400});if(b.id)await env.DB.prepare("UPDATE music_tracks SET title=?,artist=?,src=?,position=?,active=? WHERE id=?").bind(String(b.title).trim(),String(b.artist||"").trim(),String(b.src).trim(),Number(b.position)||0,b.active===false?0:1,Number(b.id)).run();else await env.DB.prepare("INSERT INTO music_tracks(title,artist,src,position,active,created_at) VALUES(?,?,?,?,?,?)").bind(String(b.title).trim(),String(b.artist||"").trim(),String(b.src).trim(),Number(b.position)||0,b.active===false?0:1,now()).run()}
 else if(b.action==="status"){const allowed:any={order:"orders",payment:"payment_requests",support:"support_threads"},table=allowed[b.target];if(!table)return NextResponse.json({error:"Geçersiz işlem"},{status:400});const previous:any=b.target==="payment"?await env.DB.prepare("SELECT status,amount,customer_name,email FROM payment_requests WHERE id=?").bind(b.id).first():null;await env.DB.prepare(`UPDATE ${table} SET status=? WHERE id=?`).bind(b.status,b.id).run();if(b.target==="payment"&&b.status==="approved"&&previous&&previous.status!=="approved"){const time=now();await env.DB.batch([env.DB.prepare("INSERT INTO transactions(type,amount,category,description,status,created_at) VALUES('income',?,'Bakiye yükleme',?,'completed',?)").bind(previous.amount,"Ödeme #"+b.id+" · "+previous.customer_name,time),env.DB.prepare("INSERT INTO customer_balances(email,balance,created_at,updated_at) VALUES(?,?,?,?) ON CONFLICT(email) DO UPDATE SET balance=balance+excluded.balance,updated_at=excluded.updated_at").bind(String(previous.email||"").trim().toLowerCase(),previous.amount,time,time)])}}
 else if(b.action==="retry-order"){const o:any=await env.DB.prepare("SELECT provider_service_id,link,quantity FROM orders WHERE id=?").bind(b.id).first();if(!o)return NextResponse.json({error:"Sipariş bulunamadı"},{status:404});if(!o.provider_service_id)return NextResponse.json({error:"Tedarikçi servis ID eksik"},{status:400});const result=await forwardOrder({service:o.provider_service_id,link:o.link,quantity:o.quantity});await env.DB.prepare("UPDATE orders SET provider_order_id=?,provider_error=?,status=? WHERE id=?").bind(result.providerOrderId||"",result.error||"",result.forwarded?"processing":"pending",b.id).run();if(!result.forwarded)return NextResponse.json({error:result.error},{status:502})}
 else if(b.action==="reply"){await env.DB.prepare("INSERT INTO support_messages(thread_id,sender,message,created_at) VALUES(?,'admin',?,?)").bind(b.threadId,b.message,now()).run();await env.DB.prepare("UPDATE support_threads SET updated_at=? WHERE id=?").bind(now(),b.threadId).run()}
 else return NextResponse.json({error:"Geçersiz işlem"},{status:400});return NextResponse.json({ok:true})
}
export async function DELETE(r:Request){if(!await isAdmin())return NextResponse.json({error:"Yetkisiz"},{status:403});const u=new URL(r.url),kind=u.searchParams.get("kind"),id=Number(u.searchParams.get("id"));const allowed:any={transaction:"transactions",method:"payment_methods",music:"music_tracks",review:"customer_reviews"};if(!allowed[kind]||!id)return NextResponse.json({error:"Geçersiz"},{status:400});if(kind==="review")await ensureReviews();await env.DB.prepare(`DELETE FROM ${allowed[kind]} WHERE id=?`).bind(id).run();return NextResponse.json({ok:true})}
