import { env } from "cloudflare:workers";
import { providerSalePrice } from "@/lib/provider-pricing";
import { providerConfig, providerId, type ProviderId } from "@/lib/providers";
import { catalogAnnouncementStatement, flushCatalogAnnouncements } from "@/lib/telegram-announcements";
type ProviderService={type?:string;service?:number|string;id?:number|string;name?:string;description?:string;platform?:string;category?:string|{name?:string;slug?:string};rate?:string|number;pricing?:{rate?:string|number;currency?:string;unit?:string};min?:number|string;max?:number|string;limits?:{min?:number|string;max?:number|string};features?:Record<string,boolean>;refill?:boolean|string;cancel?:boolean|string;fields?:any[];average_time_seconds?:number;is_active?:boolean};
const key=()=>String((env as any).SMM_PROVIDER_API_KEY||"");
function v2Url(){const base=String((env as any).SMM_PROVIDER_API_URL||"https://panelfollows.com/api/v2").replace(/\/$/,"");return /\/api\/v[23](?:\/tr)?$/i.test(base)?base.replace(/\/api\/v[23](?:\/tr)?$/i,"/api/v2"):base+"/api/v2"}
async function v2(action:string,id?:ProviderId){const p=providerConfig(id);if(!p.key)throw new Error(`${p.name} API anahtarı hosting ortamında tanımlı değil.`);const response=await fetch(id==="smmxserver"?p.url:v2Url(),{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded",accept:"application/json"},body:new URLSearchParams({key:p.key,action}).toString()}),payload:any=await response.json().catch(()=>({}));if(!response.ok||payload.error)throw new Error(String(payload.error||payload.message||`${p.name} HTTP ${response.status}`).split(p.key).join("[gizli]").slice(0,300));return payload}
async function v3Services(){const base=v2Url().replace(/\/api\/v2\/?$/i,"/api/v3"),all:ProviderService[]=[];let cursor="";for(let page=0;page<100;page++){const url=new URL(`${base}/services`);url.searchParams.set("limit","100");url.searchParams.set("lang","tr");if(cursor)url.searchParams.set("starting_after",cursor);const response=await fetch(url,{headers:{Authorization:`Bearer ${key()}`,"Accept-Language":"tr"}}),payload:any=await response.json().catch(()=>({}));if(!response.ok||payload.error)throw new Error(String(payload.error||payload.message||`PanelFollows v3 HTTP ${response.status}`).slice(0,300));const rows:ProviderService[]=Array.isArray(payload)?payload:payload.data||payload.services||[];all.push(...rows);if(!rows.length||(!payload.has_more&&rows.length<100))break;cursor=String(payload.next_cursor||payload.next||payload.cursor||rows.at(-1)?.id||"");if(!cursor)break}return all}
function titleCase(value:string){return value.replace(/[-_]+/g," ").replace(/\b\w/g,letter=>letter.toLocaleUpperCase("tr-TR")).trim()}
function inferPlatform(service:ProviderService){const haystack=`${service.platform||""} ${typeof service.category==="string"?service.category:""} ${service.name||""}`.toLocaleLowerCase("tr-TR"),platforms:Array<[RegExp,string]>=[[/instagram/,"Instagram"],[/tiktok/,"TikTok"],[/youtube/,"YouTube"],[/telegram/,"Telegram"],[/facebook/,"Facebook"],[/(twitter|\bx\b)/,"X / Twitter"],[/whatsapp/,"WhatsApp"],[/twitch/,"Twitch"],[/spotify/,"Spotify"],[/kick/,"Kick"],[/discord/,"Discord"],[/linkedin/,"LinkedIn"],[/threads/,"Threads"],[/soundcloud/,"SoundCloud"],[/pinterest/,"Pinterest"],[/snapchat/,"Snapchat"],[/reddit/,"Reddit"],[/google/,"Google"]];return platforms.find(([pattern])=>pattern.test(haystack))?.[1]||titleCase(service.platform||"Diğer")}
function inferCategory(service:ProviderService,platform:string){const supplied=typeof service.category==="string"?service.category:service.category?.name||service.category?.slug;if(supplied?.trim())return titleCase(supplied);const name=(service.name||"").toLocaleLowerCase("tr-TR"),kinds:Array<[RegExp,string]>=[[/takipçi|followers?/,"Takipçi"],[/beğeni|likes?/,"Beğeni"],[/izlenme|görüntülenme|views?|plays?/,"İzlenme"],[/abone|subscribers?/,"Abone"],[/yorum|comments?/,"Yorum"],[/üye|members?/,"Üye"],[/paylaşım|shares?|repost/,"Paylaşım"],[/kaydetme|saves?/,"Kaydetme"],[/reaksiyon|reactions?/,"Reaksiyon"],[/canlı|live/,"Canlı Yayın"],[/hikaye|story/,"Hikâye"],[/trafik|traffic/,"Trafik"]];return kinds.find(([pattern])=>pattern.test(name))?.[1]||`${platform} Diğer Hizmetler`}
async function usdTryRate(strict=false){const override=Number((env as any).SMM_PROVIDER_USD_TRY_RATE||0);if(override>0)return override;try{const xml=await fetch("https://www.tcmb.gov.tr/kurlar/today.xml",{cf:{cacheTtl:3600}} as any).then(response=>response.text()),block=xml.match(/<Currency[^>]+CurrencyCode="USD"[\s\S]*?<\/Currency>/i)?.[0]||"";const rate=Number(block.match(/<ForexSelling>([\d.]+)<\/ForexSelling>/i)?.[1]);if(rate>0)return rate;if(strict)throw new Error("USD/TRY kuru alınamadı; fiyatlar değiştirilmedi.");return 1}catch{if(strict)throw new Error("USD/TRY kuru alınamadı; fiyatlar değiştirilmedi.");return 1}}
export async function fetchProviderCatalog(id:ProviderId="panelfollows"){const config=providerConfig(id);let services:ProviderService[];const configuredVersion=String(config.version);if(configuredVersion==="2")try{const payload=await v2("services",id);services=Array.isArray(payload)?payload:payload.services||payload.data||[]}catch(error){if(id!=="panelfollows"||!(error instanceof Error)||!/(invalid api key|unauthorized|forbidden|authentication)/i.test(error.message))throw error;services=await v3Services()}else services=await v3Services();if(!services.length)throw new Error(`${config.name} hizmet listesi boş döndü.`);const fx=await usdTryRate(id==="smmxserver");return services.filter(item=>item.is_active!==false&&(id!=="smmxserver"||["Default","Package","Custom Comments","Comment Likes","Poll","SEO"].includes(item.type||"Default"))).map(item=>{const platform=inferPlatform(item),category=inferCategory(item,platform),currency=String(item.pricing?.currency||"USD").toUpperCase(),rawRate=Number(item.pricing?.rate??item.rate??0),costTry=currency==="TRY"?rawRate:rawRate*fx,priceUnit=item.pricing?.unit==="per_order"||(id==="smmxserver"&&item.type==="Package")?"per_order":"per_1000",features=item.features||{refill:/true|refill|telafi|♻/i.test(String(item.refill||"")),cancel:/true|cancel|iptal/i.test(String(item.cancel||""))},fields=Array.isArray(item.fields)?item.fields:id==="smmxserver"?(item.type==="Custom Comments"?[{name:"comments",label:"Yorumlar (her satıra bir yorum)",type:"text_lines",required:true}]:item.type==="Comment Likes"?[{name:"username",label:"Kullanıcı adı",type:"string",required:true}]:item.type==="Poll"?[{name:"answer_number",label:"Anket cevap numarası",type:"integer",min:1,required:true}]:item.type==="SEO"?[{name:"keywords",label:"Anahtar kelimeler",type:"string",required:true}]:[]):[];return{providerId:id,providerServiceId:String(item.service??item.id),platform,category,name:item.name?.trim()||`${platform} ${category}`,description:item.description?.trim()||`${platform} için otomatik teslimat hizmeti.`,minOrder:Number(item.limits?.min??item.min??10)||10,maxOrder:Number(item.limits?.max??item.max??10000)||10000,costPrice:Math.max(0,Math.round(costTry*100)),salePrice:providerSalePrice(Math.max(0,Math.round(costTry*100))),priceUnit,providerFeatures:JSON.stringify(features),providerFields:JSON.stringify(fields),averageTimeSeconds:Math.max(0,Number(item.average_time_seconds||0))}})}
export async function fetchProviderBalance(id:ProviderId="panelfollows"){const payload=await v2("balance",id);return{balance:Number(payload.balance||0),currency:String(payload.currency||"USD")}}
export async function syncProviderCatalog(id:ProviderId="panelfollows"){
 id=providerId(id);
 
 const lockKey=`provider_catalog_lock:${id}`,token=crypto.randomUUID(),at=Math.floor(Date.now()/1000);
 await env.DB.prepare("INSERT INTO site_settings(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at WHERE site_settings.updated_at < ?").bind(lockKey,token,at,at-300).run();
 const lock:any=await env.DB.prepare("SELECT value FROM site_settings WHERE key=?").bind(lockKey).first();
 if(lock?.value!==token)throw new Error("Bu tedarikçi kataloğu zaten güncelleniyor.");
 try{const result=await syncCatalogRows(id);const time=Math.floor(Date.now()/1000);await env.DB.prepare("INSERT INTO site_settings(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").bind(`provider_catalog_last_sync:${id}`,String(time),time).run();return result;}
 finally{await env.DB.prepare("DELETE FROM site_settings WHERE key=? AND value=?").bind(lockKey,token).run();}
}
async function syncCatalogRows(id:ProviderId){
 id=providerId(id);const services=await fetchProviderCatalog(id);if(!services.length)throw new Error("Desteklenen hizmet bulunamadı; mevcut katalog korunuyor.");
 const existing=await env.DB.prepare("SELECT id,provider_service_id FROM services WHERE provider_id=? AND provider_service_id<>''").bind(id).all();
 const existingRows=existing.results as any[];
 const byProviderId=new Map(existingRows.map(row=>[String(row.provider_service_id),Number(row.id)]));
 const currentProviderIds=new Set(services.map(service=>service.providerServiceId));
 let added=0,updated=0,disabled=0;
 const batches:any[][]=[];
 let currentBatch:any[]=[];
 const createdAt=Math.floor(Date.now()/1000);
 for(const service of services){
  const currentId=byProviderId.get(service.providerServiceId);
  if(currentId){
   updated++;
   const group=[env.DB.prepare("UPDATE services SET platform=?,category=?,name=?,min_order=?,max_order=?,cost_price=?,sale_price=CASE WHEN price_override=1 THEN sale_price ELSE ? END,price_unit=?,provider_features=?,provider_fields=?,average_time_seconds=?,description=?,active=1 WHERE id=?").bind(service.platform,service.category,service.name,service.minOrder,service.maxOrder,service.costPrice,service.salePrice,service.priceUnit,service.providerFeatures,service.providerFields,service.averageTimeSeconds,service.description,currentId)];
   if(currentBatch.length+group.length>100){batches.push(currentBatch);currentBatch=[]}currentBatch.push(...group);
  }else{
   added++;
   const group=[env.DB.prepare("INSERT INTO services(platform,category,name,provider_id,provider_service_id,min_order,max_order,cost_price,sale_price,price_unit,provider_features,provider_fields,average_time_seconds,description,active,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,?)").bind(service.platform,service.category,service.name,id,service.providerServiceId,service.minOrder,service.maxOrder,service.costPrice,service.salePrice,service.priceUnit,service.providerFeatures,service.providerFields,service.averageTimeSeconds,service.description,createdAt),...[catalogAnnouncementStatement({providerServiceId:service.providerServiceId,platform:service.platform,category:service.category,name:service.name,salePrice:service.salePrice,priceUnit:service.priceUnit},`${id === "panelfollows" ? "provider" : id}-${encodeURIComponent(service.providerServiceId)}`,createdAt)]];
   if(currentBatch.length+group.length>100){batches.push(currentBatch);currentBatch=[]}currentBatch.push(...group);
  }
 }
 // Keep historical service rows and orders intact, but hide services removed from the supplier.
 const staleIds=existingRows.filter(row=>!currentProviderIds.has(String(row.provider_service_id))).map(row=>Number(row.id));
 disabled=staleIds.length;
 for(let i=0;i<staleIds.length;i+=100){
  const staleBatch=staleIds.slice(i,i+100).map(id=>env.DB.prepare("UPDATE services SET active=0 WHERE id=?").bind(id));
  if(staleBatch.length)batches.push(staleBatch);
 }
 if(currentBatch.length)batches.push(currentBatch);
 for(const batch of batches)if(batch.length)await env.DB.batch(batch);
 const notification=await flushCatalogAnnouncements();
 return{providerId:id,total:services.length,added,updated,disabled,telegramSent:notification.sent,telegramConfigured:notification.configured};
}
