import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
export const services = sqliteTable("services", {
  id: integer("id").primaryKey({ autoIncrement: true }), platform: text("platform").notNull(), category: text("category").notNull(), name: text("name").notNull(), providerServiceId: text("provider_service_id").notNull().default(""), minOrder: integer("min_order").notNull().default(10), maxOrder: integer("max_order").notNull().default(10000), costPrice: integer("cost_price").notNull().default(0), salePrice: integer("sale_price").notNull().default(0), description: text("description").notNull().default(""), active: integer("active", { mode: "boolean" }).notNull().default(true), createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const transactions=sqliteTable("transactions",{id:integer("id").primaryKey({autoIncrement:true}),type:text("type").notNull(),amount:integer("amount").notNull(),category:text("category").notNull(),description:text("description").notNull().default(""),status:text("status").notNull().default("completed"),createdAt:integer("created_at",{mode:"timestamp"}).notNull()});
export const paymentMethods=sqliteTable("payment_methods",{id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull(),type:text("type").notNull(),instructions:text("instructions").notNull().default(""),active:integer("active",{mode:"boolean"}).notNull().default(true),createdAt:integer("created_at",{mode:"timestamp"}).notNull()});
export const paymentRequests=sqliteTable("payment_requests",{id:integer("id").primaryKey({autoIncrement:true}),customerName:text("customer_name").notNull(),email:text("email").notNull().default(""),amount:integer("amount").notNull(),method:text("method").notNull(),note:text("note").notNull().default(""),status:text("status").notNull().default("pending"),createdAt:integer("created_at",{mode:"timestamp"}).notNull()});
export const orders=sqliteTable("orders",{id:integer("id").primaryKey({autoIncrement:true}),customerName:text("customer_name").notNull(),serviceName:text("service_name").notNull(),serviceId:integer("service_id"),providerServiceId:text("provider_service_id").notNull().default(""),providerOrderId:text("provider_order_id").notNull().default(""),providerError:text("provider_error").notNull().default(""),link:text("link").notNull(),quantity:integer("quantity").notNull(),amount:integer("amount").notNull(),status:text("status").notNull().default("pending"),createdAt:integer("created_at",{mode:"timestamp"}).notNull()});
export const supportThreads=sqliteTable("support_threads",{id:integer("id").primaryKey({autoIncrement:true}),publicKey:text("public_key").notNull().unique(),customerName:text("customer_name").notNull(),email:text("email").notNull().default(""),status:text("status").notNull().default("open"),createdAt:integer("created_at",{mode:"timestamp"}).notNull(),updatedAt:integer("updated_at",{mode:"timestamp"}).notNull()});
export const supportMessages=sqliteTable("support_messages",{id:integer("id").primaryKey({autoIncrement:true}),threadId:integer("thread_id").notNull(),sender:text("sender").notNull(),message:text("message").notNull(),createdAt:integer("created_at",{mode:"timestamp"}).notNull()});
export const customerBalances=sqliteTable("customer_balances",{id:integer("id").primaryKey({autoIncrement:true}),email:text("email").notNull().unique(),balance:integer("balance").notNull().default(0),createdAt:integer("created_at",{mode:"timestamp"}).notNull(),updatedAt:integer("updated_at",{mode:"timestamp"}).notNull()});
export const customerUsers=sqliteTable("customer_users",{id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull(),email:text("email").notNull().unique(),passwordHash:text("password_hash").notNull(),passwordSalt:text("password_salt").notNull(),avatar:text("avatar").notNull().default("star"),createdAt:integer("created_at",{mode:"timestamp"}).notNull()});
export const customerSessions=sqliteTable("customer_sessions",{id:integer("id").primaryKey({autoIncrement:true}),userId:integer("user_id").notNull(),tokenHash:text("token_hash").notNull().unique(),expiresAt:integer("expires_at",{mode:"timestamp"}).notNull(),createdAt:integer("created_at",{mode:"timestamp"}).notNull()},t=>[index("idx_customer_sessions_expiry").on(t.expiresAt)]);
export const shopierPayments=sqliteTable("shopier_payments",{id:integer("id").primaryKey({autoIncrement:true}),paymentRef:text("payment_ref").notNull().unique(),shopierOrderId:text("shopier_order_id").unique(),customerEmail:text("customer_email").notNull(),amount:integer("amount").notNull(),status:text("status").notNull().default("created"),credited:integer("credited",{mode:"boolean"}).notNull().default(false),rawEventHash:text("raw_event_hash").notNull().default(""),createdAt:integer("created_at",{mode:"timestamp"}).notNull(),updatedAt:integer("updated_at",{mode:"timestamp"}).notNull()},t=>[index("idx_shopier_payments_event_hash").on(t.rawEventHash),index("idx_shopier_payments_customer").on(t.customerEmail,t.createdAt)]);
export const adminLoginAttempts=sqliteTable("admin_login_attempts",{id:integer("id").primaryKey({autoIncrement:true}),fingerprint:text("fingerprint").notNull(),success:integer("success",{mode:"boolean"}).notNull().default(false),createdAt:integer("created_at",{mode:"timestamp"}).notNull()},t=>[index("idx_admin_login_attempts_fingerprint_time").on(t.fingerprint,t.createdAt)]);
export const siteSettings=sqliteTable("site_settings",{key:text("key").primaryKey(),value:text("value").notNull().default(""),updatedAt:integer("updated_at",{mode:"timestamp"}).notNull()});
export const musicTracks=sqliteTable("music_tracks",{id:integer("id").primaryKey({autoIncrement:true}),title:text("title").notNull(),artist:text("artist").notNull().default(""),src:text("src").notNull(),position:integer("position").notNull().default(0),active:integer("active",{mode:"boolean"}).notNull().default(true),createdAt:integer("created_at",{mode:"timestamp"}).notNull()});

export const accountChallenges=sqliteTable("account_challenges",{id:text("id").primaryKey(),answerHash:text("answer_hash").notNull(),expiresAt:integer("expires_at").notNull(),createdAt:integer("created_at").notNull()},t=>[index("idx_account_challenges_expiry").on(t.expiresAt)]);
