import { index, integer, primaryKey, sqliteTable, text } from "drizzle-orm/sqlite-core";
export const services = sqliteTable("services", {
  id: integer("id").primaryKey({ autoIncrement: true }), platform: text("platform").notNull(), category: text("category").notNull(), name: text("name").notNull(), providerId: text("provider_id").notNull().default("panelfollows"), providerServiceId: text("provider_service_id").notNull().default(""), minOrder: integer("min_order").notNull().default(10), maxOrder: integer("max_order").notNull().default(10000), costPrice: integer("cost_price").notNull().default(0), salePrice: integer("sale_price").notNull().default(0), priceOverride: integer("price_override", { mode: "boolean" }).notNull().default(false), priceUnit: text("price_unit").notNull().default("per_1000"), providerFeatures: text("provider_features").notNull().default("{}"), providerFields: text("provider_fields").notNull().default("[]"), averageTimeSeconds: integer("average_time_seconds").notNull().default(0), description: text("description").notNull().default(""), active: integer("active", { mode: "boolean" }).notNull().default(true), createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const transactions=sqliteTable("transactions",{id:integer("id").primaryKey({autoIncrement:true}),type:text("type").notNull(),amount:integer("amount").notNull(),category:text("category").notNull(),description:text("description").notNull().default(""),status:text("status").notNull().default("completed"),createdAt:integer("created_at",{mode:"timestamp"}).notNull()});
export const paymentMethods=sqliteTable("payment_methods",{id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull(),type:text("type").notNull(),instructions:text("instructions").notNull().default(""),active:integer("active",{mode:"boolean"}).notNull().default(true),createdAt:integer("created_at",{mode:"timestamp"}).notNull()});
export const paymentRequests=sqliteTable("payment_requests",{id:integer("id").primaryKey({autoIncrement:true}),customerName:text("customer_name").notNull(),email:text("email").notNull().default(""),amount:integer("amount").notNull(),bonusAmount:integer("bonus_amount").notNull().default(0),method:text("method").notNull(),note:text("note").notNull().default(""),status:text("status").notNull().default("pending"),createdAt:integer("created_at",{mode:"timestamp"}).notNull()});
export const orders=sqliteTable("orders",{id:integer("id").primaryKey({autoIncrement:true}),customerName:text("customer_name").notNull(),customerEmail:text("customer_email").notNull().default(""),serviceName:text("service_name").notNull(),serviceId:integer("service_id"),providerId:text("provider_id").notNull().default("panelfollows"),providerServiceId:text("provider_service_id").notNull().default(""),providerOrderId:text("provider_order_id").notNull().default(""),providerError:text("provider_error").notNull().default(""),providerRefillId:text("provider_refill_id").notNull().default(""),providerAction:text("provider_action").notNull().default(""),providerSyncedAt:integer("provider_synced_at").notNull().default(0),link:text("link").notNull(),quantity:integer("quantity").notNull(),amount:integer("amount").notNull(),status:text("status").notNull().default("pending"),source:text("source").notNull().default("site"),externalReference:text("external_reference").notNull().default(""),externalSaleAmount:integer("external_sale_amount").notNull().default(0),providerCost:integer("provider_cost").notNull().default(0),createdAt:integer("created_at",{mode:"timestamp"}).notNull()});
export const supportThreads=sqliteTable("support_threads",{id:integer("id").primaryKey({autoIncrement:true}),publicKey:text("public_key").notNull().unique(),customerName:text("customer_name").notNull(),email:text("email").notNull().default(""),status:text("status").notNull().default("open"),createdAt:integer("created_at",{mode:"timestamp"}).notNull(),updatedAt:integer("updated_at",{mode:"timestamp"}).notNull()});
export const supportMessages=sqliteTable("support_messages",{id:integer("id").primaryKey({autoIncrement:true}),threadId:integer("thread_id").notNull(),sender:text("sender").notNull(),message:text("message").notNull(),createdAt:integer("created_at",{mode:"timestamp"}).notNull()});
export const customerBalances=sqliteTable("customer_balances",{id:integer("id").primaryKey({autoIncrement:true}),email:text("email").notNull().unique(),balance:integer("balance").notNull().default(0),createdAt:integer("created_at",{mode:"timestamp"}).notNull(),updatedAt:integer("updated_at",{mode:"timestamp"}).notNull()});
export const customerUsers=sqliteTable("customer_users",{id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull(),email:text("email").notNull().unique(),passwordHash:text("password_hash").notNull(),passwordSalt:text("password_salt").notNull(),avatar:text("avatar").notNull().default("man-1"),createdAt:integer("created_at",{mode:"timestamp"}).notNull(),emailVerifiedAt:integer("email_verified_at")});
export const customerSessions=sqliteTable("customer_sessions",{id:integer("id").primaryKey({autoIncrement:true}),userId:integer("user_id").notNull(),tokenHash:text("token_hash").notNull().unique(),expiresAt:integer("expires_at",{mode:"timestamp"}).notNull(),createdAt:integer("created_at",{mode:"timestamp"}).notNull()},t=>[index("idx_customer_sessions_expiry").on(t.expiresAt)]);
export const shopierPayments=sqliteTable("shopier_payments",{id:integer("id").primaryKey({autoIncrement:true}),paymentRef:text("payment_ref").notNull().unique(),shopierOrderId:text("shopier_order_id").unique(),customerEmail:text("customer_email").notNull(),amount:integer("amount").notNull(),status:text("status").notNull().default("created"),credited:integer("credited",{mode:"boolean"}).notNull().default(false),rawEventHash:text("raw_event_hash").notNull().default(""),createdAt:integer("created_at",{mode:"timestamp"}).notNull(),updatedAt:integer("updated_at",{mode:"timestamp"}).notNull()},t=>[index("idx_shopier_payments_event_hash").on(t.rawEventHash),index("idx_shopier_payments_customer").on(t.customerEmail,t.createdAt)]);
export const adminLoginAttempts=sqliteTable("admin_login_attempts",{id:integer("id").primaryKey({autoIncrement:true}),fingerprint:text("fingerprint").notNull(),success:integer("success",{mode:"boolean"}).notNull().default(false),createdAt:integer("created_at",{mode:"timestamp"}).notNull()},t=>[index("idx_admin_login_attempts_fingerprint_time").on(t.fingerprint,t.createdAt)]);
export const siteSettings=sqliteTable("site_settings",{key:text("key").primaryKey(),value:text("value").notNull().default(""),updatedAt:integer("updated_at",{mode:"timestamp"}).notNull()});
export const musicTracks=sqliteTable("music_tracks",{id:integer("id").primaryKey({autoIncrement:true}),title:text("title").notNull(),artist:text("artist").notNull().default(""),src:text("src").notNull(),position:integer("position").notNull().default(0),active:integer("active",{mode:"boolean"}).notNull().default(true),createdAt:integer("created_at",{mode:"timestamp"}).notNull()});

export const accountChallenges=sqliteTable("account_challenges",{id:text("id").primaryKey(),answerHash:text("answer_hash").notNull(),expiresAt:integer("expires_at").notNull(),createdAt:integer("created_at").notNull()},t=>[index("idx_account_challenges_expiry").on(t.expiresAt)]);
export const customerRewardEvents=sqliteTable("customer_reward_events",{id:integer("id").primaryKey({autoIncrement:true}),customerEmail:text("customer_email").notNull(),eventType:text("event_type").notNull(),orderId:integer("order_id"),spendAmount:integer("spend_amount").notNull().default(0),points:integer("points").notNull(),balanceCredit:integer("balance_credit").notNull().default(0),createdAt:integer("created_at").notNull()},t=>[index("idx_customer_reward_events_email_id").on(t.customerEmail,t.id)]);

export const customerPasswordResets=sqliteTable("customer_password_resets",{id:integer("id").primaryKey({autoIncrement:true}),userId:integer("user_id").notNull(),tokenHash:text("token_hash").notNull().unique(),expiresAt:integer("expires_at").notNull(),usedAt:integer("used_at"),createdAt:integer("created_at").notNull(),attempts:integer("attempts").notNull().default(0)},t=>[index("idx_customer_password_resets_user_created").on(t.userId,t.createdAt)]);
export const customerEmailVerifications=sqliteTable("customer_email_verifications",{id:integer("id").primaryKey({autoIncrement:true}),userId:integer("user_id").notNull(),tokenHash:text("token_hash").notNull().unique(),expiresAt:integer("expires_at").notNull(),usedAt:integer("used_at"),createdAt:integer("created_at").notNull()},t=>[index("idx_customer_email_verifications_user_created").on(t.userId,t.createdAt)]);
export const customerNotifications=sqliteTable("customer_notifications",{id:integer("id").primaryKey({autoIncrement:true}),customerEmail:text("customer_email").notNull(),kind:text("kind").notNull(),title:text("title").notNull(),body:text("body").notNull(),translations:text("translations").notNull().default("{}"),orderId:integer("order_id"),readAt:integer("read_at"),createdAt:integer("created_at").notNull()},t=>[index("idx_customer_notifications_email_id").on(t.customerEmail,t.id)]);

export const adminRecords=sqliteTable("admin_records",{id:integer("id").primaryKey({autoIncrement:true}),module:text("module").notNull(),data:text("data").notNull().default("{}"),active:integer("active").notNull().default(1),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull()},t=>[index("idx_admin_records_module").on(t.module,t.active)]);
export const adminActivity=sqliteTable("admin_activity",{id:integer("id").primaryKey({autoIncrement:true}),actor:text("actor").notNull(),kind:text("kind").notNull(),action:text("action").notNull(),target:text("target").notNull().default(""),createdAt:integer("created_at").notNull()},t=>[index("idx_admin_activity_time").on(t.kind,t.createdAt)]);
export const adminStaff=sqliteTable("admin_staff",{id:integer("id").primaryKey({autoIncrement:true}),username:text("username").notNull().unique(),name:text("name").notNull(),passwordHash:text("password_hash").notNull(),passwordSalt:text("password_salt").notNull(),roleId:integer("role_id").notNull().references(()=>adminRecords.id),active:integer("active").notNull().default(1),createdAt:integer("created_at").notNull()});
export const adminStaffSessions=sqliteTable("admin_staff_sessions",{tokenHash:text("token_hash").primaryKey(),staffId:integer("staff_id").notNull().references(()=>adminStaff.id),expiresAt:integer("expires_at").notNull()});
export const automationJobs=sqliteTable("automation_jobs",{id:integer("id").primaryKey({autoIncrement:true}),requestKey:text("request_key").notNull().unique(),kind:text("kind").notNull(),customerEmail:text("customer_email").notNull(),customerName:text("customer_name").notNull(),serviceId:integer("service_id").notNull(),serviceName:text("service_name").notNull(),providerId:text("provider_id").notNull(),providerServiceId:text("provider_service_id").notNull(),link:text("link").notNull(),quantity:integer("quantity").notNull(),unitAmount:integer("unit_amount").notNull(),unitCost:integer("unit_cost").notNull(),totalRuns:integer("total_runs").notNull(),completedRuns:integer("completed_runs").notNull().default(0),intervalMinutes:integer("interval_minutes").notNull(),nextRunAt:integer("next_run_at").notNull(),state:text("state").notNull().default("active"),error:text("error").notNull().default(""),createdAt:integer("created_at").notNull()},t=>[index("idx_automation_due").on(t.state,t.nextRunAt)]);
export const automationRuns=sqliteTable("automation_runs",{jobId:integer("job_id").notNull().references(()=>automationJobs.id),runNumber:integer("run_number").notNull(),orderId:integer("order_id"),state:text("state").notNull(),createdAt:integer("created_at").notNull()},t=>[primaryKey({columns:[t.jobId,t.runNumber]})]);
