const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite'),root=path.join(__dirname,'..'),db=new DatabaseSync(':memory:');
for(const f of fs.readdirSync(path.join(root,'drizzle')).filter(x=>x.endsWith('.sql')).sort())db.exec(fs.readFileSync(path.join(root,'drizzle',f),'utf8'));
const env={};env.DB={prepare(sql){let args=[];return{bind(...v){args=v;return this},async all(){return{results:db.prepare(sql).all(...args)}},async first(){return db.prepare(sql).get(...args)||null},async run(){return /^SELECT/i.test(sql)?this.all():{meta:{changes:Number(db.prepare(sql).run(...args).changes)}}}}},async batch(xs){const out=[];for(const x of xs)out.push(await x.run());return out}};
const loaded={};function load(file){if(loaded[file])return loaded[file];let js=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,m={exports:{}};new Function('require','module','exports',js)(name=>name==='cloudflare:workers'?{env}:name==='next/server'?{NextResponse:{json:(data,options)=>({data,status:options?.status||200})}}:name.startsWith('@/')?load(name.slice(2)+'.ts'):require(name),m,m.exports);return loaded[file]=m.exports}
async function main(){const t=load('lib/localization.ts');let calls=0;env.AI={run:async(_,input)=>{calls++;return{response:JSON.stringify(JSON.parse(input.messages[1].content).map(x=>x.replace('takipçi','followers').replace('Sipariş','Order')))}}};
// A catalog page must not scan the entire order table for every service.
db.exec("INSERT INTO services(platform,category,name,min_order,max_order,sale_price,cost_price,created_at) VALUES('Instagram','Followers','Fixture',1,100,100,50,0);INSERT INTO orders(customer_name,customer_email,service_id,service_name,link,quantity,amount,status,created_at) VALUES('Fixture','fixture@example.invalid',1,'Fixture','https://example.invalid',10,100,'completed',0)");
const countsSQL='SELECT id,COALESCE(t.orderCount,0) orderCount FROM services LEFT JOIN (SELECT service_id,COUNT(*) orderCount FROM orders GROUP BY service_id) t ON t.service_id=services.id WHERE active=1 ORDER BY id DESC';assert.equal(db.prepare(countsSQL).get().orderCount,1);const plan=db.prepare('EXPLAIN QUERY PLAN '+countsSQL).all().map(x=>x.detail).join('\n');assert.ok(!plan.includes('CORRELATED'),'order counts computed once');assert.ok(plan.includes('orders_service_count_idx'),'order count uses covering index');
let cached=null;global.caches={default:{put:async(_,response)=>{cached=response.clone()},match:async()=>cached?.clone(),delete:async()=>{cached=null}}};const catalogCache=load('lib/catalog-cache.ts');await catalogCache.cacheCatalog(new Response('[{"id":1}]',{headers:{'cdn-cache-control':'no-store'}}));assert.equal((await catalogCache.cachedCatalog()).headers.get('cache-control'),'public, max-age=300');await catalogCache.invalidateCatalogCache();assert.equal(await catalogCache.cachedCatalog(),null);delete global.caches;
const source='Instagram 1.000 takipçi — 65% — ₺12,50';const first=await t.translateTexts('en',[source,source]);assert.equal(first.translations[source],'Instagram 1.000 followers — 65% — ₺12,50');assert.equal(first.pending.length,0);await t.translateTexts('en',[source]);assert.equal(calls,1,'database cache prevents repeat AI charges');
const hash=await t.textHash(source);db.prepare('UPDATE translation_cache SET manual=1,translated=? WHERE source_hash=?').run('Manual correct translation',hash);assert.equal((await t.translateTexts('en',[source])).translations[source],'Manual correct translation');assert.equal((await t.manualTranslations('en'))[source],'Manual correct translation');
env.AI.run=async()=>({response:'["Changed quantity 5000"]'});const bad='1000 Sipariş';assert.equal((await t.translateTexts('fr',[bad])).pending.length,1);assert.equal(db.prepare('SELECT COUNT(*) n FROM translation_cache WHERE locale=?').get('fr').n,0,'reject altered quantities');
db.prepare('UPDATE translation_usage SET characters=250000').run();const before=calls;env.AI.run=async()=>{calls++;return{response:'[]'}};const quota=await t.translateTexts('uk',['Yeni hizmet']);assert.equal(quota.pending.length,1);assert.equal(calls,before,'daily budget prevents AI call');await t.runTranslationQueue();assert.equal(db.prepare('SELECT attempts FROM translation_queue WHERE locale=?').get('uk').attempts,0,'quota does not consume queue retry');
const api=load('app/api/localization/route.ts');let r=await api.POST(new Request('https://example.invalid/api/localization',{method:'POST',headers:{'content-type':'application/json',origin:'https://attacker.invalid'},body:'{}'}));assert.equal(r.status,403);r=await api.POST(new Request('https://example.invalid/api/localization',{method:'POST',body:JSON.stringify({locale:'xx',texts:['Test']})}));assert.equal(r.status,400);r=await api.GET(new Request('https://example.invalid/api/localization?locale=en'));assert.equal(r.data.translations[source],'Manual correct translation');
const fx=load('app/api/exchange-rates/route.ts');global.fetch=async()=>({ok:true,json:async()=>({result:'success',base_code:'TRY',time_last_update_unix:1,rates:{TRY:1,USD:.02,EUR:.018,GBP:.016,UAH:.83,RUB:1.9,BRL:.1}})});assert.equal((await fx.GET()).data.rates.BRL,.1);db.prepare("UPDATE site_settings SET value=? WHERE key='display_exchange_rates'").run(JSON.stringify({rates:{TRY:1,USD:.02},fetchedAt:1}));global.fetch=async()=>{throw Error('offline')};r=await fx.GET();assert.equal(r.data.stale,true);assert.equal(r.data.rates.USD,.02);db.prepare("DELETE FROM site_settings WHERE key='display_exchange_rates'").run();assert.equal((await fx.GET()).status,503,'no invented currency rate when provider unavailable');
console.log('PASS: localization cache, manual priority, quantity/brand protection, daily budget and retry, origin and locale validation, live FX and stale fallback. No external calls.');}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>db.close());
