import { env } from "cloudflare:workers";
import { NextResponse } from "next/server";
import { digest,passwordHash,randomHex } from "@/lib/customer-auth";
import { verifyAccountChallenge } from "@/lib/account-challenge";
import { sendTransactionalEmail,siteBaseUrl } from "@/lib/mailer";
export async function POST(request:Request){
 let stage="request";try{const body=await request.json() as any,name=String(body.name||"").trim(),email=String(body.email||"").trim().toLowerCase(),password=String(body.password||"");
 if(!await verifyAccountChallenge(request,body))return NextResponse.json({error:"İnsan doğrulaması başarısız veya süresi dolmuş. Lütfen tekrar doğrula."},{status:400});
 if(name.length<2||email.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<8||password.length>128)return NextResponse.json({error:"Ad, geçerli e-posta ve 8–128 karakterli şifre gerekli."},{status:400});
 stage="lookup";
 if(await env.DB.prepare("SELECT id FROM customer_users WHERE email=?").bind(email).first())return NextResponse.json({error:"Bu e-posta zaten kayıtlı. Giriş yapmayı veya şifreni yenilemeyi dene."},{status:409});
 stage="password";const salt=randomHex(16),hash=await passwordHash(password,salt),created=Math.floor(Date.now()/1000);stage="user";const createdUser:any=await env.DB.prepare("INSERT INTO customer_users(name,email,password_hash,password_salt,avatar,created_at) VALUES(?,?,?,?,?,?) RETURNING id").bind(name,email,hash,salt,"man-1",created).first();
 const userId=Number(createdUser?.id);if(!Number.isInteger(userId)||userId<1)throw new Error("user_id");stage="balance";await env.DB.prepare("INSERT OR IGNORE INTO customer_balances(email,balance,created_at,updated_at) VALUES(?,0,?,?)").bind(email,created,created).run();
 stage="verification";const token=randomHex(32),tokenHash=await digest(token),expiresAt=created+24*60*60;await env.DB.prepare("INSERT INTO customer_email_verifications(user_id,token_hash,expires_at,created_at) VALUES(?,?,?,?)").bind(userId,tokenHash,expiresAt,created).run();
 const verifyUrl=`${siteBaseUrl()}/site/#email-verify=${encodeURIComponent(token)}`;
 const delivery=await sendTransactionalEmail({to:email,subject:"ElTurco SMM e-posta adresini doğrula",text:`ElTurco SMM hesabını etkinleştirmek için bu bağlantıyı 24 saat içinde aç:\n${verifyUrl}\n\nBağlantıyı sen istemediysen bu e-postayı yok say.`,html:`<div style="background:#07111a;padding:32px;font-family:Arial,sans-serif;color:#eef3f6"><div style="max-width:520px;margin:auto;border:1px solid #233b46;border-radius:18px;padding:28px;background:#0b1821"><p style="color:#f6c954;font-size:12px;letter-spacing:2px;font-weight:bold">ELTURCO SMM</p><h1 style="font-size:24px">E-postanı doğrula</h1><p style="color:#b2c0c8;line-height:1.6">Merhaba ${name.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!))}, hesabını etkinleştirmek için e-posta adresini doğrula. Bağlantı 24 saat geçerlidir.</p><a href="${verifyUrl}" style="display:inline-block;background:#f4c94f;color:#15191b;text-decoration:none;font-weight:bold;padding:13px 18px;border-radius:10px">E-postamı doğrula ve hesabı etkinleştir</a><p style="margin-top:24px;color:#8798a2;font-size:12px">Bu hesabı sen oluşturmadıysan bu e-postayı yok say.</p></div></div>`});
 if(!delivery.sent){await env.DB.batch([env.DB.prepare("DELETE FROM customer_email_verifications WHERE user_id=?").bind(userId),env.DB.prepare("DELETE FROM customer_balances WHERE email=?").bind(email),env.DB.prepare("DELETE FROM customer_users WHERE id=? AND email_verified_at IS NULL").bind(userId)]);return NextResponse.json({error:"Doğrulama e-postası gönderilemedi. Biraz sonra tekrar dene veya destek ekibine ulaş."},{status:503})}
 return NextResponse.json({ok:true,verificationRequired:true,message:"Doğrulama bağlantısını e-posta adresine gönderdik. Gelen kutunu ve gereksiz e-posta klasörünü kontrol et; bağlantıya tıklamadan giriş yapamazsın."},{status:200});
 }catch(error){const message=error instanceof Error?error.message:"";console.error("customer_register_failed",{stage,message});if(message.toLowerCase().includes("unique"))return NextResponse.json({error:"Bu e-posta zaten kayıtlı."},{status:409});return NextResponse.json({error:"Kayıt şu anda tamamlanamadı. Lütfen tekrar dene.",code:"REGISTER_"+stage.toUpperCase()},{status:500})}
}
